//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Fweb.rc
//
#define IDB_BIGTOOLBAR24                101
#define IDB_BIGTOOLBAR24B               102
#define IDB_BIGTOOLBAR24R               103
#define IDB_BULLET                      104
#define IDB_FRAME1_BULLET1              105
#define IDB_FRAME1_BULLET2              106
#define IDB_FRAME1_BULLET3              107
#define IDC_ABOUTIMAGE                  109
#define IDC_ADDCAMP_ADD                 110
#define IDC_ADDCAMP_CHANGE              111
#define IDC_ADDCAMP_COST                112
#define IDC_ADDCAMP_LIST                113
#define IDC_ADDCAMP_NAME                114
#define IDC_ADDCAMP_PATTERN             115
#define IDC_ADDCAMP_REM                 116
#define IDC_APPLYALL                    117
#define IDC_BUTTON1                     118
#define IDC_BUTTON2                     119
#define IDC_BUTTON3                     120
#define IDC_BUTTON4                     121
#define IDC_CLEARCACHE                  122
#define IDC_COMBODATABASETABLE          123
#define IDC_COOKIEVAR                   124
#define IDC_CUSTOM_DATA                 125
#define IDC_CUSTOM_DATE                 126
#define IDC_CUSTOM_INFO                 127
#define IDC_CUSTOM_POS                  128
#define IDC_CUSTOM_POSTXT               129
#define IDC_CUSTOM_SEP                  130
#define IDC_CUSTOM_TIME                 131
#define IDC_CUSTOM_USE                  132
#define IDC_DATABASETABLECANCEL         133
#define IDC_DATABASETABLEOK             134
#define IDC_DATEEND                     135
#define IDC_DATEOFFSET                  136
#define IDC_DATEOVERIDE                 137
#define IDC_DATESTART                   138
#define IDC_DB_BROWSE                   139
#define IDC_DB_DELETE                   140
#define IDC_DB_NAME                     141
#define IDC_DB_NONE                     142
#define IDC_DB_SELECT_COMPACT           143
#define IDC_DESCCANCEL                  144
#define IDC_DB_SELECT_EXTENDED          145
#define IDC_DESCOK                      146
#define IDC_DOWNLOADLOGS                147
#define IDC_EDIT1                       148
#define IDC_EDIT2                       149
#define IDC_EDIT3                       150
#define IDC_EDIT4                       151
#define IDC_EDITLOGTABLE                152
#define IDC_EDITLOGTABLECANCELL         153
#define IDC_EDITLOGTABLEOK              154
#define IDC_EDITPATH_ADD                155
#define IDC_EDITPATH_BROWSE             156
#define IDC_EDITPATH_CHANGE             157
#define IDC_EDITPATH_DEL                158
#define IDC_EDITPATH_HOST               159
#define IDC_EDITPATH_PATH               160
#define IDC_EXTEDIT                     161
#define IDC_FILELOCATIONBROWSE          162
#define IDC_FILELOCATIONCANCEL          163
#define IDC_FILELOCATIONEDIT            164
#define IDC_FILELOCATIONOK              165
#define IDC_FILEVIEW                    166
#define IDC_FILEVIEWNAME                167
#define IDC_FILTERIN_ADD                168
#define IDC_FILTERIN_CHANGE             169
#define IDC_FILTERIN_DATA               170
#define IDC_FILTERIN_LIST               171
#define IDC_FILTERIN_REM                172
#define IDC_FILTERIN1                   173
#define IDC_FILTERIN2                   174
#define IDC_FILTERIN3                   175
#define IDC_FILTEROUT_ADD               176
#define IDC_FILTEROUT_CHANGE            177
#define IDC_FILTEROUT_CLEAR             178
#define IDC_FILTEROUT_DATA              179
#define IDC_FILTEROUT_LIST              180
#define IDC_FILTEROUT_REM               181
#define IDC_FILTEROUT1                  182
#define IDC_FILTEROUT2                  183
#define IDC_FILTEROUT3                  184
#define IDC_FLUSHTXT1                   185
#define IDC_FRAME2_FILE_NAME            186
#define IDC_FRAME2_SEL_BUTT             187
#define IDC_FRAME3_RADIO1               188
#define IDC_FRAME3_RADIO2               189
#define IDC_FRAME3_RADIO3               190
#define IDC_FRAME4_SEL_BUTT             191
#define IDC_FTPCANCEL                   192
#define IDC_FTPHOST                     193
#define IDC_FTPOK                       194
#define IDC_FTPPASS                     195
#define IDC_FTPPATH                     196
#define IDC_FTPUSER                     197
#define IDC_APPHELP                     198
#define IDC_APPLOGO                     199
#define IDC_GLOB_PAGEADD                200
#define IDC_GLOB_PAGEDEFAULT            201
#define IDC_GLOB_PAGEEDIT               202
#define IDC_GLOB_PAGEREM                203
#define IDC_GLOB_TITLE                  204
#define IDC_LANGTOKEN_FIND              205
#define IDC_LANGTOKEN_FINDPREV          206
#define IDC_LANGTOKEN_FINDTEXT          207
#define IDC_LANGTOKEN_LANG              208
#define IDC_LANGTOKEN_LIST              209
#define IDC_LANGTOKEN_TEXT              210
#define IDC_LANGTOKEN_UPDATE            211
#define IDC_LOCATION                    212
#define IDC_LOGLIST                     213
#define IDC_MISC2                       214
#define IDC_NOTIFY_DB                   215
#define IDC_NOTIFY_FIELD                216
#define IDC_NOTIFY_LOGIC                217
#define IDC_NOTIFY_ON1                  218
#define IDC_NOTIFY_ON2                  219
#define IDC_NOTIFY_ON3                  220
#define IDC_NOTIFYEMAIL                 221
#define IDC_OUTDIR                      222
#define IDC_PP_COMPRESSLOG              223
#define IDC_PP_DELETELOG                224
#define IDC_PP_DELETEREPORT             225
#define IDC_PP_EMAIL                    226
#define IDC_PP_EMAILFROM                227
#define IDC_PP_EMAILON                  228
#define IDC_PP_EMAILSMTP                229
#define IDC_PP_EMAILSUB                 230
#define IDC_PP_HOST                     231
#define IDC_PP_HOST2                    232
#define IDC_PP_MSG                      233
#define IDC_PP_PASSWD                   234
#define IDC_PP_PASSWD2                  235
#define IDC_PP_PATH                     236
#define IDC_PP_PATH2                    237
#define IDC_PP_UPLOADLOG                238
#define IDC_PP_UPLOADREPORT             239
#define IDC_PP_USER                     240
#define IDC_PP_USER2                    241
#define IDC_PP_ZIPREPORT                242
#define IDC_PP_UPLOADFOLDER             243
#define IDC_PRE_BROWSE                  244
#define IDC_PRE_HOST                    245
#define IDC_PRE_ON                      246
#define IDC_PRE_PASSWD                  247
#define IDC_PRE_PATH                    248
#define IDC_PRE_USER                    249
#define IDC_PREF_BANDWIDTH              250
#define IDC_PREF_HEADTITLE              251
#define IDC_PREF_LANG                   252
#define IDC_PREF_LEFTSIDE               253
#define IDC_PREF_PDF_ADV_CANCEL         254
#define IDC_PREF_PDF_ADV_OK             255
#define IDC_PREF_PDF_ADVANCED           256
#define IDC_PREF_PDF_BANNERFILE         257
#define IDC_PREF_PDF_BOTTOMMARGIN       258
#define IDC_PREF_PDF_BROWSEBANNERFILE   259
#define IDC_PREF_PDF_FONT               260
#define IDC_PREF_PDF_FONTCOLOR          261
#define IDC_PREF_PDF_FONTSIZE           262
#define IDC_PREF_PDF_FONTSTYLE          263
#define IDC_PREF_PDF_GRAPHFONT          264
#define IDC_PREF_PDF_GRAPHFONTSIZE      265
#define IDC_PREF_PDF_LEFTMARGIN         266
#define IDC_PREF_PDF_MINCOLHEADSCHARS   267
#define IDC_PREF_PDF_PAGEHEIGHT         268
#define IDC_PREF_PDF_PAGENUMBERINGPOS   269
#define IDC_PREF_PDF_PAGESIZE           270
#define IDC_PREF_PDF_PAGEWIDTH          271
#define IDC_PREF_PDF_REDUCEDATAFONTSIZE 272
#define IDC_PREF_PDF_REDUCEDATAFONTSIZEPER 273
#define IDC_PREF_PDF_REDUCELARGESTDATACOL 274
#define IDC_PREF_PDF_RIGHTMARGIN        275
#define IDC_PREF_PDF_SHOWBANNER         276
#define IDC_PREF_PDF_SPACING            277
#define IDC_PREF_PDF_SPACINGSIZE        278
#define IDC_PREF_PDF_TABLETEXTNAME      279
#define IDC_PREF_PDF_TEXTWRAP           280
#define IDC_PREF_PDF_TOPMARGIN          281
#define IDC_PREF_PDF_TRUNCATETEXT       282
#define IDC_PREF_QINDEX                 283
#define IDC_PREF_REMOTETITLE            284
#define IDC_PREF_SHADOW                 285
#define IDC_PREF_TIMESTAT               286
#define IDC_PREFADD_ADD                 287
#define IDC_PREFADD_CHANGE              288
#define IDC_PREFADD_LIST                289
#define IDC_PREFADD_NAME                290
#define IDC_PREFADD_PATTERN1            291
#define IDC_PREFADD_PATTERN2            292
#define IDC_PREFADD_REM                 293
#define IDC_PREFBOT_ADD                 294
#define IDC_PREFBOT_CHANGE              295
#define IDC_PREFBOT_LIST                296
#define IDC_PREFBOT_NAME                297
#define IDC_PREFBOT_PATTERN             298
#define IDC_PREFBOT_REM                 299
#define IDC_PREFCANCEL                  300
#define IDC_PREFDEFAULT                 301
#define IDC_PREFFILT_SRCADD             302
#define IDC_PREFFILT_SRCCLR             303
#define IDC_PREFFILT_SRCLIST            304
#define IDC_PREFFILT_SRCNAME            305
#define IDC_PREFFILT_SRCREM             306
#define IDC_PREFFTP_PASSIVE             307
#define IDC_PREFGEN_DATESTYLE           308
#define IDC_PREFGEN_DNSCACHE            309
#define IDC_PREFGEN_DNSNO               310
#define IDC_PREFGEN_DNSNUM              311
#define IDC_PREFGEN_DNSYES              312
#define IDC_PREFGEN_FILTERZERO          313
#define IDC_PREFGEN_FLUSH               314
#define IDC_PREFGEN_GTYPE               315
#define IDC_PREFGEN_IGNOREBOOKMARK      316
#define IDC_PREFGEN_IGNORECASE          317
#define IDC_PREFGEN_IGNORESELF          318
#define IDC_PREFGEN_IGNOREUSERS         319
#define IDC_PREFGEN_INDEXFILE           320
#define IDC_PREFGEN_INSERT              321
#define IDC_PREFGEN_OUT                 322
#define IDC_PREFGEN_RETAINVAR           323
#define IDC_PREFGEN_RETAINVARLIST       324
#define IDC_PREFGEN_SPLITDATE           325
#define IDC_PREFGEN_TYPE                326
#define IDC_PREFGEN_URL                 327
#define IDC_PREFGEN_USECGI              328
#define IDC_PREFGRAPH_3DBARS            329
#define IDC_PREFGRAPH_CORP              330
#define IDC_PREFGRAPH_WEBPAL            331
#define IDC_PREFGRAPH_WIDER             332
#define IDC_PREFGRP_ADD                 333
#define IDC_PREFGRP_CHANGE              334
#define IDC_PREFGRP_LIST                335
#define IDC_PREFGRP_NAME                336
#define IDC_PREFGRP_PATTERN             337
#define IDC_PREFGRP_REM                 338
#define IDC_PREFHTML_FOOT               339
#define IDC_PREFHTML_HEAD               340
#define IDC_PREFHTML_RGB1               341
#define IDC_PREFHTML_RGB10              342
#define IDC_PREFHTML_RGB11              343
#define IDC_PREFHTML_RGB2               344
#define IDC_PREFHTML_RGB3               345
#define IDC_PREFHTML_RGB4               346
#define IDC_PREFHTML_RGB5               347
#define IDC_PREFHTML_RGB6               348
#define IDC_PREFHTML_RGB7               349
#define IDC_PREFHTML_RGB8               350
#define IDC_PREFHTML_RGB9               351
#define IDC_PREFIMG_RGB1                352
#define IDC_COMBO_BILLINGFORMAT         352
#define IDC_PREFIMG_RGB10               353
#define IDC_PREFIMG_RGB2                354
#define IDC_PREFIMG_RGB3                355
#define IDC_PREFIMG_RGB4                356
#define IDC_PREFIMG_RGB5                357
#define IDC_PREFIMG_RGB6                358
#define IDC_PREFIMG_RGB7                359
#define IDC_PREFIMG_RGB8                360
#define IDC_PREFIMG_RGB9                361
#define IDC_PREFNOTIFY_ADD              362
#define IDC_PREFNOTIFY_CLR              363
#define IDC_PREFNOTIFY_LIST             364
#define IDC_PREFNOTIFY_NAME             365
#define IDC_PREFNOTIFY_REM              366
#define IDC_PREFOK                      367
#define IDC_PREFORG_ADD                 368
#define IDC_PREFORG_CHANGE              369
#define IDC_PREFORG_DEFAULT             370
#define IDC_PREFORG_DEL                 371
#define IDC_PREFORG_LIST                372
#define IDC_PREFORG_NAME                373
#define IDC_PREFORG_PATTERN             374
#define IDC_PREFREF_ADD                 375
#define IDC_PREFREF_CHANGE              376
#define IDC_PREFREF_LIST                377
#define IDC_PREFREF_NAME                378
#define IDC_PREFREF_PATTERN             379
#define IDC_PREFREF_REM                 380
#define IDC_PREFREVERT                  381
#define IDC_PREFROUTER_ADD              382
#define IDC_PROXY_ADD                   383
#define IDC_PREFROUTER_CHANGE           384
#define IDC_PROXY_CHANGE                385
#define IDC_PREFROUTER_CLR              386
#define IDC_PROXY_CLR                   387
#define IDC_PREFROUTER_LIST             388
#define IDC_PROXY_LIST                  389
#define IDC_PREFROUTER_NAME             390
#define IDC_PROXY_NAME                  391
#define IDC_PREFROUTER_REM              392
#define IDC_PROXY_REM                   393
#define IDC_PREFS                       394
#define IDC_PREFS_EDITPATH              395
#define IDC_PREFS_LISTRECT              396
#define IDC_PREFSRC_CHANGE              397
#define IDC_PREFSTAT_SESSIONTIME        398
#define IDC_PREFSTAT_SESSIONTXT         399
#define IDC_PREFVD_ADD                  400
#define IDC_PREFVD_CHANGE               401
#define IDC_PREFVD_CLUSTER              402
#define IDC_PREFVD_CLUSTERINFO          403
#define IDC_PREFVD_CLUSTERNUM           404
#define IDC_PREFVD_COST                 405
#define IDC_PREFVD_LIST                 406
#define IDC_PREFVD_NAME                 407
#define IDC_PREFVD_NUM                  408
#define IDC_PREFVD_PATTERN              409
#define IDC_PREFVD_REM                  410
#define IDC_PREFVD_SEQDIR               411
#define IDC_PREFVD_SLEEP                412
#define IDC_PREFVD_TYPE                 413
#define IDC_PREPROC_BROWSE              414
#define IDC_PREPROC_DEL                 415
#define IDC_PREPROC_DEST                416
#define IDC_PROCESS                     417
#define IDC_REGCANCEL                   418
#define IDC_REGDEMO                     419
#define IDC_REGNAME                     420
#define IDC_REGOK                       421
#define IDC_REGORG                      422
#define IDC_REGSERIAL                   423
#define IDC_REGTXT1                     424
#define IDC_REGTXT2                     425
#define IDC_REGTXT3                     426
#define IDC_REGTXT4                     427
#define IDC_REGTXT5                     428
#define IDC_REMOTECONNECT               429
#define IDC_REMOTEIP                    430
#define IDC_REMOTEON                    431
#define IDC_REMOTEPASSWD                432
#define IDC_REMOTEPORT                  433
#define IDC_REPORTTITLE                 434
#define IDC_SCHED                       435
#define IDC_FONTNAME                    436
#define IDC_SCHED_ACTIVE                437
#define IDC_FONTSIZE                    438
#define IDC_SCHED_ADD                   439
#define IDC_SCHED_ADDLOG                441
#define IDC_SCHED_CANCEL                442
#define IDC_SCHED_CLEAR                 443
#define IDC_SCHED_CURRENTTIME           444
#define IDC_SCHED_DATE                  445
#define IDC_SCHED_DATEADJUST            446
#define IDC_SCHED_DEL                   447
#define IDC_SCHED_DISABLE               448
#define IDC_SCHED_EDIT                  449
#define IDC_SCHED_EDITOK                450
#define IDC_SCHED_EDITPREFS             451
#define IDC_SCHED_KEYACCEL              452
#define IDC_SCHED_LISTRECT              453
#define IDC_SCHED_LOGFILE               454
#define IDC_SCHED_NAME                  455
#define IDC_SCHED_NUM                   456
#define IDC_SCHED_NUMTYPE               457
#define IDC_SCHED_OK                    458
#define IDC_SCHED_PREFSFILE             459
#define IDC_SCHED_REPORTFILE            460
#define IDC_SCHED_RUNNOW                461
#define IDC_SCHED_SELECTLOG             463
#define IDC_SCHED_SELECTPREFS           464
#define IDC_SCHED_TIME                  465
#define IDC_SCHED_TIMEADJUST            466
#define IDC_SCHED_UPLOAD                467
#define IDC_SCHED_VIEW                  468
#define IDC_SCHED_VIEWLOG               469
#define IDC_SCHEMES                     470
#define IDC_SELECTLOGTABLECOMB          471
#define IDC_SELECTLOGTABLEOK            472
#define IDC_SELECTLOGTABLEOKCANCEL      473
#define IDC_SHOWLIST                    474
#define IDC_SORTING                     475
#define IDC_SPLASHIMAGE                 476
#define IDC_STAT_DESC                   477
#define IDC_STAT_GRAPH                  478
#define IDC_STAT_TABLE                  479
#define IDC_STATDEFAULT                 480
#define IDC_STATEDIT                    481
#define IDC_STATEDIT_NAME               482
#define IDC_STATEDITDESC                483
#define IDC_STATFILTER                  484
#define IDC_STATFILTER2                 485
#define IDC_STATFILTERTXT               486
#define IDC_STATI                       487
#define IDC_STATIIDC_PREFVD_MONTHLYC    488
#define IDC_SUPP_CANCEL                 489
#define IDC_SUPP_CLR                    490
#define IDC_SUPP_EMAIL                  491
#define IDC_SUPP_OK                     492
#define IDC_SUPP_PASS                   493
#define IDC_SUPPEDIT_CANCEL             494
#define IDC_SUPPEDIT_CLR                495
#define IDC_SUPPEDIT_EMAIL              496
#define IDC_SUPPEDIT_NEW                497
#define IDC_SUPPEDIT_OK                 498
#define IDC_SUPPEDIT_OLD                499
#define IDC_SUPPEDIT_VERIFY             500
#define IDC_TAB_ADDS                    501
#define IDC_TAB_ANALYSIS                502
#define IDC_TAB_CUSTOM                  503
#define IDC_TAB_FILTER                  504
#define IDC_TAB_POSTPROC                505
#define IDC_TAB_PREPROC                 506
#define IDC_TAB_REPORT                  507
#define IDC_TAB_ROUTER                  508
#define IDC_TAB_PROXY                   509
#define IDC_TAB_STATS                   510
#define IDC_TAB_VDOMAINS                511
#define IDC_TABSIZE                     512
#define IDC_TOKENS                      513
#define IDC_STATSTYLES                  514
#define IDC_TOOLBARIMAGE                515
#define IDC_URLVAR                      516
#define IDC_USEDESC                     517
#define IDC_VDMULTIDIR                  518
#define IDC_VDREPORTBY                  519
#define IDC_VDSORTBY                    520
#define IDC_VDTOTAL                     521
#define IDC_VIEW                        522
#define IDC_VIEWSCROLL                  523
#define IDC_WEBON                       524
#define IDC_WIZARD_CANCEL               525
#define IDC_WIZARD_NEXT                 526
#define IDC_WIZARD_PREV                 527
#define IDC_WIZARD4_OUTPUT_LOC          528
#define IDC_XPROGRESS                   529
#define IDC_XSTATUS                     530
#define IDD_CHANGEPASS                  531
#define IDD_DIALOGDATABASETABLE         532
#define IDD_ENTERLOGTABLEDlg            533
#define IDD_FILELOCATIONDlg             534
#define IDD_MAINTOOLBAR                 535
#define IDD_SELECTLOGTABLEDlg           536
#define IDD_SUPPORTPASS                 537
#define IDD_XMAINTOOLBAR                538
#define IDI_LOG_ICON                    539
#define IDI_LOG_ICON1                   540
#define IDI_LOG_ICON2                   541
#define IDI_EXPAND1                     542
#define IDI_EXPAND2                     543
#define IDI_CHECKOFF                    544
#define IDI_CHECKON                     545
#define IDI_STATITEM                    546
#define IDS_ABOUT                       547
#define IDS_ADDCAMP_ADD                 548
#define IDS_ADDCAMP_COST                549
#define IDS_ADDCAMP_NAME                550
#define IDS_ADDCAMP_PATTERN             551
#define IDS_ADDCAMP_REM                 552
#define IDS_ADDHEADER                   553
#define IDS_ADDHEADER2                  554
#define IDS_APPLY_ALL                   555
#define IDS_APPLY_GROUP                 556
#define IDS_APPLYALL                    557
#define IDS_APR                         558
#define IDS_AUG                         559
#define IDS_BACKGROUND                  560
#define IDS_BUILD                       561
#define IDS_BUILTON                     562
#define IDS_CANCELFILEMAKER             563
#define IDS_CANCELLED                   564
#define IDS_CANNOTEDIT                  565
#define IDS_CLEAN                       566
#define IDS_CLEARCACHE                  567
#define IDS_COLORSCHEME_BASIC           568
#define IDS_COLORSCHEME_BLAND           569
#define IDS_COLORSCHEME_BLUE            570
#define IDS_COLORSCHEME_DEFAULT         571
#define IDS_COLORSCHEME_GREY            572
#define IDS_COLORSCHEME_ICE             573
#define IDS_COLORSCHEME_RANDOM          574
#define IDS_COLORSCHEME_WILD            575
#define IDS_COMMENTS                    576
#define IDS_COMPRESSDONE                577
#define IDS_COMPRESSED                  578
#define IDS_COMPRESSING                 579
#define IDS_CONFIG                      580
#define IDS_CONNECT                     581
#define IDS_CONNECTED                   582
#define IDS_CONNECTINGTO                583
#define IDS_CONNECTTOREMOTE             584
#define IDS_COOKIEVAR                   585
#define IDS_COPYINGFILE                 586
#define IDS_COUNTRIES                   587
#define IDS_CUSTOM_DATA                 588
#define IDS_CUSTOM_DATE                 589
#define IDS_CUSTOM_INFO                 590
#define IDS_CUSTOM_POS                  591
#define IDS_CUSTOM_SEP                  592
#define IDS_CUSTOM_TIME                 593
#define IDS_CUSTOM_USE                  594
#define IDS_DATEEND                     595
#define IDS_DATEFMT                     596
#define IDS_DATEFORMAT                  597
#define IDS_DATEOFFSET                  598
#define IDS_DATEOVERIDE                 599
#define IDS_DATES                       600
#define IDS_DATESTART                   601
#define IDS_DATETOKENS                  602
#define IDS_DEC                         603
#define IDS_DELETEFTP                   604
#define IDS_DISCONNECT                  605
#define IDS_DISCONREMOTE                606
#define IDS_DNSCLEARED                  607
#define IDS_DNSCOMPLETE                 608
#define IDS_DONE                        609
#define IDS_DOWNLOADING                 610
#define IDS_DOWNLOADINGKB               611
#define IDS_DOWNLOADSTOP                612
#define IDS_EDITPATH                    613
#define IDS_EDITSCHEDULE                614
#define IDS_EDITSET                     615
#define IDS_EMAILNOTIFY                 616
#define IDS_ENDSERVICE                  617
#define IDS_ERR_BADLOG                  618
#define IDS_ERR_CANTOPENLOG             619
#define IDS_ERR_CANTSAVE                620
#define IDS_ERR_CONNECTING              621
#define IDS_ERR_DATE1                   622
#define IDS_ERR_DATE2                   623
#define IDS_ERR_DATE3                   624
#define IDS_ERR_DATERANGE               625
#define IDS_ERR_FILEFAILED              626
#define IDS_ERR_FTPREAD                 627
#define IDS_ERR_FTPWRITE                628
#define IDS_ERR_MAKEDIR                 629
#define IDS_ERR_NOFILTER                630
#define IDS_ERR_NOSETTINGS              631
#define IDS_ERR_OUTPUT                  632
#define IDS_ERR_POSTPROC                633
#define IDS_ERR_PROCESS                 634
#define IDS_ERR_REGFAILED               635
#define IDS_ERR_SETTINGSBAD             636
#define IDS_ERR_SETTINGSFAILED          637
#define IDS_ERR_UPLOADFAIL              638
#define IDS_ERR_ZEROBYTE                639
#define IDS_EXT_AUDIO                   640
#define IDS_EXT_DOWN                    641
#define IDS_EXT_PAGES                   642
#define IDS_EXT_VIDEO                   643
#define IDS_EXTEDIT                     644
#define IDS_FAILED                      645
#define IDS_FAILEDCONNECT               646
#define IDS_FAILEDLISTEN                647
#define IDS_FAILEDMAKEDIR               648
#define IDS_FAILEDREAD                  649
#define IDS_FAILEDSOCKET                650
#define IDS_FAILEDTODOWNLOAD            651
#define IDS_FAILEDWRITE                 652
#define IDS_FEB                         653
#define IDS_FIELDFMT                    654
#define IDS_FILTER_ADD                  655
#define IDS_FILTER_CHANGE               656
#define IDS_FILTER_REM                  657
#define IDS_FILTER1                     658
#define IDS_FILTER2                     659
#define IDS_FILTER3                     660
#define IDS_FILTERIN_DATA               661
#define IDS_FILTERS                     662
#define IDS_FRAMEDHTML                  663
#define IDS_GENERAL_LABELS              664
#define IDS_GETURLTITLE                 665
#define IDS_GLOB_PAGEADD                666
#define IDS_GLOB_PAGECLR                667
#define IDS_GLOB_PAGEREM                668
#define IDS_GROUPHEADER                 669
#define IDS_HIDELIST                    670
#define IDS_ICON_NAMES                  671
#define IDS_ICON_NAMESENT               672
#define IDS_IMAGETYPE                   673
#define IDS_INFO                        674
#define IDS_INSTALLNTS                  675
#define IDS_INSTALLNTSBOOT              676
#define IDS_JAN                         677
#define IDS_JUL                         678
#define IDS_JUN                         679
#define IDS_LANG                        680
#define IDS_LANGBUILDER_LISTTITLES      681
#define IDS_LANGTOKEN_EXIT              682
#define IDS_LANGTOKEN_FIND              683
#define IDS_LANGTOKEN_FINDTEXT          684
#define IDS_LANGTOKEN_LANG              685
#define IDS_LANGTOKEN_LIST              686
#define IDS_LANGTOKEN_SAVEAS            687
#define IDS_LANGTOKEN_TEXT              688
#define IDS_LANGTOKEN_UPDATE            689
#define IDS_LITTLEDISKSPACE             690
#define IDS_LOADDATABASE                691
#define IDS_LOADSETFILE                 692
#define IDS_LOADSKIN                    693
#define IDS_LOCATION                    694
#define IDS_LOGLIST_COL1                695
#define IDS_LOGLIST_COL2                696
#define IDS_LOGLIST_COL3                697
#define IDS_LOGLIST_COL4                698
#define IDS_MAILSENT                    699
#define IDS_MAKEDEFAULT                 700
#define IDS_MAKEDIR                     701
#define IDS_MAKEFILEDIR                 702
#define IDS_MAKEZIP                     703
#define IDS_MAR                         704
#define IDS_MAY                         705
#define IDS_MENU_ABOUT                  706
#define IDS_MENU_ACWWW                  707
#define IDS_MENU_BACKGROUNDGRAD         708
#define IDS_MENU_CHECKFORUPDATE         709
#define IDS_MENU_CLEARLIST              710
#define IDS_MENU_ENDSERVICE             711
#define IDS_MENU_EXIT                   712
#define IDS_MENU_FTPPROCESS             713
#define IDS_MENU_GROW                   714
#define IDS_MENU_HELP                   715
#define IDS_MENU_INSTALLNTS             716
#define IDS_MENU_MONITORFILE            717
#define IDS_MENU_NEW                    718
#define IDS_MENU_NEWAPP                 719
#define IDS_MENU_ONLINEMANUAL           720
#define IDS_MENU_OPEN                   721
#define IDS_MENU_ORDERWWW               722
#define IDS_MENU_PREFS                  723
#define IDS_MENU_PROCESS                724
#define IDS_MENU_REGISTERNOW            725
#define IDS_MENU_REGISTERSERIAL         726
#define IDS_MENU_REMOTECONNECT          727
#define IDS_MENU_REMOTEDISCONNECT       728
#define IDS_MENU_REMOVENTS              729
#define IDS_MENU_SAVE                   730
#define IDS_MENU_SAVEAS                 731
#define IDS_MENU_SCHEDULE               732
#define IDS_MENU_SHOWNTSERVICES         733
#define IDS_MENU_SHRINK                 734
#define IDS_MENU_STARTUPSERVICE         735
#define IDS_MENU_STOP                   736
#define IDS_MENU_SUPPORTWWW             737
#define IDS_MENU_UPDATEONOFF            738
#define IDS_MENU_VIEWHTML               739
#define IDS_MENU_WIZARD                 740
#define IDS_MSG_CLEARSCH                741
#define IDS_MSG_NOREPORT                742
#define IDS_MSG_OPENYESNO               743
#define IDS_MSG_SAVESETTINGS            744
#define IDS_NETINIT_ERR                 745
#define IDS_NEWSKIN                     746
#define IDS_NODISKSPACE                 747
#define IDS_NOSETTINGSFILE              748
#define IDS_NOTABLE                     749
#define IDS_NOTENOUGH                   750
#define IDS_NOV                         751
#define IDS_OCT                         752
#define IDS_OK                          753
#define IDS_OPENFILEMAKER               754
#define IDS_OPTIONS_OFF                 755
#define IDS_OPTIONS_ON                  756
#define IDS_ORDER                       757
#define IDS_ORGANIZATIONS               758
#define IDS_ORGHEADER                   759
#define IDS_OUTDIR                      760
#define IDS_PP_BROWSE                   761
#define IDS_PP_COMPRESSLOG              762
#define IDS_PP_DELETEREPORT             763
#define IDS_PP_EMAIL                    764
#define IDS_PP_EMAILSMTP                765
#define IDS_PP_EMAILSUB                 766
#define IDS_PP_FTP                      767
#define IDS_PP_LOCATION                 768
#define IDS_PP_LOGBROWSE                769
#define IDS_PP_MSG                      770
#define IDS_PP_SENDTO                   771
#define IDS_PP_ZIPREPORT                772
#define IDS_PRE_REG                     773
#define IDS_PREF_BANDWIDTH              774
#define IDS_PREF_HEADTITLE              775
#define IDS_PREF_LANG                   776
#define IDS_PREF_LEFTSIDE               777
#define IDS_PREF_PDF_PAGESIZE           778
#define IDS_PREF_QINDEX                 779
#define IDS_PREF_REMOTETITLE            780
#define IDS_PREF_TIMESTAT               781
#define IDS_PREFADD_ADD                 782
#define IDS_PREFADD_CLR                 783
#define IDS_PREFADD_NAME                784
#define IDS_PREFADD_PATTERN1            785
#define IDS_PREFADD_PATTERN2            786
#define IDS_PREFADD_REM                 787
#define IDS_PREFGEN_DATESTYLE           788
#define IDS_PREFGEN_DNSCACHE            789
#define IDS_PREFGEN_DNSNO               790
#define IDS_PREFGEN_DNSNUM              791
#define IDS_PREFGEN_DNSYES              792
#define IDS_PREFGEN_FILTERZERO          793
#define IDS_PREFGEN_GTYPE               794
#define IDS_PREFGEN_IGNOREBOOKMARK      795
#define IDS_PREFGEN_IGNORECASE          796
#define IDS_PREFGEN_IGNORESELF          797
#define IDS_PREFGEN_INDEXFILE           798
#define IDS_PREFGEN_OUT                 799
#define IDS_PREFGEN_SPLITDATE           800
#define IDS_PREFGEN_TYPE                801
#define IDS_PREFGEN_URL                 802
#define IDS_PREFGEN_USECGI              803
#define IDS_PREFGRAPH_3DBARS            804
#define IDS_PREFGRAPH_CORP              805
#define IDS_PREFGRAPH_WEBPAL            806
#define IDS_PREFGRAPH_WIDER             807
#define IDS_PREFGRP_ADD                 808
#define IDS_PREFGRP_CLR                 809
#define IDS_PREFGRP_NAME                810
#define IDS_PREFGRP_REM                 811
#define IDS_PREFHTML_FOOT               812
#define IDS_PREFHTML_HEAD               813
#define IDS_PREFHTML_RGB1               814
#define IDS_PREFHTML_RGB2               815
#define IDS_PREFHTML_RGB3               816
#define IDS_PREFHTML_RGB4               817
#define IDS_PREFHTML_RGB5               818
#define IDS_PREFHTML_RGB6               819
#define IDS_PREFNOTIFY_ADD              820
#define IDS_PREFNOTIFY_CLR              821
#define IDS_PREFNOTIFY_NAME             822
#define IDS_PREFNOTIFY_REM              823
#define IDS_PREFORG_ADD                 824
#define IDS_PREFORG_CLR                 825
#define IDS_PREFORG_DEFAULT             826
#define IDS_PREFORG_NAME                827
#define IDS_PREFORG_REM                 828
#define IDS_PREFREF_ADD                 829
#define IDS_PREFREF_CLR                 830
#define IDS_PREFREF_NAME                831
#define IDS_PREFROUTER_ADD              832
#define IDS_PREFROUTER_CHANGE           833
#define IDS_PREFROUTER_CLR              834
#define IDS_PREFROUTER_NAME             835
#define IDS_PREFROUTER_REM              836
#define IDS_PREFSTAT_SESSIONTIME        837
#define IDS_PREFVD_ADD                  838
#define IDS_PREFVD_CLR                  839
#define IDS_PREFVD_CLUSTER              840
#define IDS_PREFVD_COST                 841
#define IDS_PREFVD_MONTHLY              842
#define IDS_PREFVD_NAME                 843
#define IDS_PREFVD_REM                  844
#define IDS_PREFVD_SEQDIR               845
#define IDS_PREFVD_WEEKLY               846
#define IDS_PREPROCESS                  847
#define IDS_PROCESSCLIENTS              848
#define IDS_PROCESSFROMLIST             849
#define IDS_PROCESSING                  850
#define IDS_PROCESSLOG                  851
#define IDS_QUIT                        852
#define IDS_RECEIVELOGLIST              853
#define IDS_REFERHEADER                 854
#define IDS_REG                         855
#define IDS_REGISTMSG1                  856
#define IDS_REGISTMSG2                  857
#define IDS_REGISTONLINE                858
#define IDS_REGNOTCREATE                859
#define IDS_REGONLINE                   860
#define IDS_REMOTEADDLOG                861
#define IDS_REMOTEDISCON                862
#define IDS_REMOTEGETCONFG              863
#define IDS_REMOTELOG                   864
#define IDS_REMOTEPROCESS               865
#define IDS_REMOTEPROCESSLIST           866
#define IDS_REMOTESHOW                  867
#define IDS_REMOTESTOP                  868
#define IDS_REMOVENTS                   869
#define IDS_REPORT_CAT                  870
#define IDS_REPORT_PDF_GRAPHFONT        871
#define IDS_REPORT_PDFFONT              872
#define IDS_REPORT_PDFFONTSTYLES        873
#define IDS_REPORT_PDFPAGENUMBERINGPOS  874
#define IDS_REPORT_PDFPAGESIZES         875
#define IDS_REPORT_PDFSPACING           876
#define IDS_REPORT_PDFTABLETEXTNAME     877
#define IDS_REPORT_PDFTRUNCATETEXT      878
#define IDS_REPORT_TITLES               879
#define IDS_REPORTFORMAT                880
#define IDS_SAVEDATABASE                881
#define IDS_SCH_CANCEL                  883
#define IDS_SCH_HEADERS                 884
#define IDS_SCH_NOEDIT                  885
#define IDS_SCH_NOEDIT2                 886
#define IDS_SCH_NOSETTINGS              887
#define IDS_SCH_SAVED                   888
#define IDS_SCHEDULEOFF                 889
#define IDS_SELECT_COMPACT_DATABASE     890
#define IDS_SELECTDOMAIN                891
#define IDS_SELECTFOLDER                892
#define IDS_SELECTLOAD                  893
#define IDS_SELECTLOADLOGLIST           894
#define IDS_SELECTLOCATION              895
#define IDS_SELECTLOG                   896
#define IDS_SELECTOUTPUT                897
#define IDS_SELECTSAVE                  898
#define IDS_SELECTSAVELOG               899
#define IDS_SELECTSAVELOGLIST           900
#define IDS_SELECTSKIN                  901
#define IDS_SENDMAILHEADER              902
#define IDS_SENFCONFIG                  903
#define IDS_SEP                         904
#define IDS_SERVER_ERRORS               905
#define IDS_SERVER_STATS                906
#define IDS_SESSION_LIST                907
#define IDS_SET                         908
#define IDS_SETTINGSSAVED               909
#define IDS_SHOWLIST                    910
#define IDS_SORTING                     911
#define IDS_STARTUPSERVICE              912
#define IDS_STAT_NEWVER                 913
#define IDS_STAT_NOUDPATES              914
#define IDS_STAT_TABLE                  915
#define IDS_STATEDIT                    916
#define IDS_STATUST_CMPT                917
#define IDS_STOPPED                     918
#define IDS_STOREFILEINTEMP             919
#define IDS_SYSTEM_INFO                 920
#define IDS_TABADDS                     921
#define IDS_TABANALYSIS                 922
#define IDS_TABCUSTOM                   923
#define IDS_TABCUSTOM2                  924
#define IDS_TABBILLING                  924
#define IDS_TABFILTERS                  925
#define IDS_TABPOSTPROC                 926
#define IDS_TABPREPROC                  927
#define IDS_TABREPORT                   928
#define IDS_TABROUTER                   929
#define IDS_TABPROXY                    930
#define IDS_TABSIZE                     931
#define IDS_TABSTATS                    932
#define IDS_TABSTATSDEBUG               933
#define IDS_TABSTATSENT                 934
#define IDS_TABVHOSTS                   935
#define IDS_TABVHOSTS2                  936
#define IDS_TIME                        937
#define IDS_TIME_RELATED                938
#define IDS_TIMEFMT                     939
#define IDS_TIMER                       940
#define IDS_TIPEDIT                     941
#define IDS_TIPAPPHELP                  942
#define IDS_TIPLISTVIEW                 943
#define IDS_TIPOPEN                     944
#define IDS_TIPPREFS2                   945
#define IDS_TIPPROCESS                  946
#define IDS_TIPPROCESS2                 947
#define IDS_TIPSCHED                    948
#define IDS_TIPSHOWLIST                 949
#define IDS_TIPTABSIZE                  950
#define IDS_TIPVDREPORTBY               951
#define IDS_TIPVDSORTBY                 952
#define IDS_TIPVIEW                     953
#define IDS_TOKENS                      954
#define IDS_TOOLBARSERVICE              955
#define IDS_UPLOADED                    956
#define IDS_UPLOADINGTO                 957
#define IDS_UPLOADLOGS                  958
#define IDS_UPLOADREPORT                959
#define IDS_USEGRAPH                    960
#define IDS_VDREPORTBY                  961
#define IDS_VDSORTBY                    962
#define IDS_VMAPHEADER                  963
#define IDS_WARN_MANYFILES              964
#define IDS_WEB                         965
#define IDS_WIZARD                      966
#define IDS_WRITEGRAPH                  967
#define IDS_WRITEGRAPH_DONE             968
#define IDS_WRITEREPORT                 969
#define IDS_WRITEREPORT_DONE            970
#define IDS_WRITINGHOST                 971
#define IDS_WRITINGREPORT               972
#define IDS_ZIPFINISH                   973
#define IDS_LANG_SAVEAS                 974
#define IDS_ADDCAMP_CHANGE              975
#define IDS_WIZARDGUIMSG                976
#define IDS_NEXT                        977
#define IDS_STRING_REMOVETHIS           978
#define IDS_CLUSTERHEADER               979
#define IDS_FILTERSTRING_0_EXCLUDE      980
#define IDS_FILTERSTRING_0_INCLUDE      981
#define IDS_FILTERSTRING_1_EXCLUDE      982
#define IDS_FILTERSTRING_1_INCLUDE      983
#define IDS_FILTERSTRING_2_EXCLUDE      984
#define IDS_FILTERSTRING_2_INCLUDE      985
#define IDS_FILTERSTRING_3_EXCLUDE      986
#define IDS_FILTERSTRING_3_INCLUDE      987
#define IDS_FILTERSTRING_4_EXCLUDE      988
#define IDS_FILTERSTRING_4_INCLUDE      989
#define IDS_FILTERSTRING_5_EXCLUDE      990
#define IDS_FILTERSTRING_5_INCLUDE      991
#define IDS_FILTERSTRING_6_EXCLUDE      992
#define IDS_FILTERSTRING_6_INCLUDE      993
#define IDS_FILTERSTRING_7_EXCLUDE      994
#define IDS_FILTERSTRING_7_INCLUDE      995
#define IDS_FILTERSTRING_8_EXCLUDE      996
#define IDS_FILTERSTRING_8_INCLUDE      997
#define IDS_FILTERSTRING_9_EXCLUDE      998
#define IDS_FILTERSTRING_9_INCLUDE      999
#define IDS_FILTERSTRING_EXACT_0_EXCLUDE 1000
#define IDS_FILTERSTRING_EXACT_0_INCLUDE 1001
#define IDS_FILTERSTRING_EXACT_1_EXCLUDE 1002
#define IDS_FILTERSTRING_EXACT_1_INCLUDE 1003
#define IDS_FILTERSTRING_EXACT_2_EXCLUDE 1004
#define IDS_FILTERSTRING_EXACT_2_INCLUDE 1005
#define IDS_FILTERSTRING_EXACT_3_EXCLUDE 1006
#define IDS_FILTERSTRING_EXACT_3_INCLUDE 1007
#define IDS_FILTERSTRING_EXACT_4_EXCLUDE 1008
#define IDS_FILTERSTRING_EXACT_4_INCLUDE 1009
#define IDS_FILTERSTRING_EXACT_5_EXCLUDE 1010
#define IDS_FILTERSTRING_EXACT_5_INCLUDE 1011
#define IDS_FILTERSTRING_EXACT_6_EXCLUDE 1012
#define IDS_FILTERSTRING_EXACT_6_INCLUDE 1013
#define IDS_FILTERSTRING_EXACT_7_EXCLUDE 1014
#define IDS_FILTERSTRING_EXACT_7_INCLUDE 1015
#define IDS_FILTERSTRING_EXACT_8_EXCLUDE 1016
#define IDS_FILTERSTRING_EXACT_8_INCLUDE 1017
#define IDS_FILTERSTRING_EXACT_9        1018
#define IDS_FILTERS_BELOW               1019
#define IDS_KEYVISITORHEADER            1020
#define IDS_HELP_CARDS                  1021
#define IDS_ROUTETOKEYPAGE              1022
#define IDC_EDIT_TIPS                   1023
#define IDS_ROUTEFROMKEYPAGE            1024
#define IDC_PREF_FOOTERLABEL            1025
#define IDS_TABREPORT2                  1026
#define IDC_PREF_FOOTERLABELTRAIL       1027
#define IDS_TABROUTES                   1028
#define IDS_ICON_NAMESFIREWALL          1029
#define IDS_MENU_CONVERT2W3C            1030
#define IDS_STATSTYLES                  1031
#define IDS_LOGLIST_COL5                1032
#define IDS_LOGLIST_COL6                1033
#define IDS_CONFIRM_DB_DELETE           1034
#define IDS_DB_DELETED_OK               1035
#define IDS_DB_DELETE_FAILED            1036
#define IDS_DB_DOES_NOT_EXIST           1037
#define IDS_MENU_CONVERT2W3C_STATUS     1038
#define IDC_BUTTON_EXPANDALL            1039
#define IDS_SELECT_EXTENDED_DATABASE    1039
#define IDC_PREFKEYVISITOR_NAME         1040
#define IDC_PREFKEYVISITOR_LIST         1041
#define IDC_PREFKEYVISITOR_ADD          1042
#define IDC_PREFKEYVISITOR_DEL          1043
#define IDC_PREFKEYVISITOR_CHANGE       1044
#define IDC_PREFKEYVISITOR_DEFAULT      1045
#define IDC_CLUSTER_NAME                1046
#define IDC_CLUSTER_IP                  1047
#define IDC_CLUSTER_LIST                1048
#define IDC_CLUSTER_ADD                 1049
#define IDC_CLUSTER_DEL                 1050
#define IDC_CLUSTER_CHANGE              1051
#define IDC_LIST_KEYPAGES               1052
#define IDC_ROUTE2KEYPAGE_ADD           1053
#define IDC_ROUTE2KEYPAGE_CHANGE        1054
#define IDC_ROUTE2KEYPAGE_REM           1055
#define IDC_ROUTE2KEYPAGE_CLEAR         1056
#define IDC_ROUTE2KEYPAGE_KEYPAGE       1057
#define IDC_ROUTE2KEYPAGE_TRACEBACK     1058
#define IDC_ROUTE2KEYPAGE_NUMBERTOREPORT 1059
#define IDC_EMAIL_TEST                  1060
#define IDC_BUTTON_DEBUG_RELOADXML      1061
#define IDC_EDIT_CONTROLID              1062
#define IDC_CLUSTER_PATTERN             1063
#define IDC_TAB_DEBUG                   1064
#define IDC_LANGTOKEN_EXIT              1065
#define IDC_LANGTOKEN_SAVEAS            1066
#define IDC_ROUTEFROMKEYPAGE_KEYPAGE    1067
#define IDC_ROUTEFROMKEYPAGE_TRACEBACK  1068
#define IDC_ROUTEFROMKEYPAGE_NUMBERTOREPORT 1069
#define IDC_ROUTEFROMKEYPAGE_LIST       1070
#define IDC_ROUTEFROMKEYPAGE_ADD        1071
#define IDC_ROUTEFROMKEYPAGE_CHANGE     1072
#define IDC_ROUTEFROMKEYPAGE_REM        1073
#define IDC_ROUTEFROMKEYPAGE_CLEAR      1074
#define IDC_DB_EXCLUDE                  1075
#define IDC_DB_REPORT                   1076
#define IDC_TAB_ROUTES                  1077
#define IDI_ICON1                       1097
#define IDC_CHECK_ENABLEBILLING         5040
#define IDC_TAB_BILLING                 5041
#define IDC_COMBO_BILLINGPERIOD         5042
#define IDC_EDIT_BILLINGSTART           5043
#define IDC_EDIT_BILLINGEND             5044
#define IDC_COMBO_BILLINGCUSTOMEREXCESSTYPE 5045
#define IDC_LIST_BILLINGCUSTOMER        5046
#define IDC_BUTTON_BILLINGCUSTOMERADD   5047
#define IDC_CHECK_BILLINGREPORT_NAME    5048
#define IDC_COMBO_BILLINGCUSTOMERFIXEDTYPE 5049
#define IDC_CHECK_BILLINGREPORT_ID      5050
#define IDC_BUTTON_BILLINGCUSTOMERDELETE 5051
#define IDC_CHECK_BILLINGREPORT_MBTRANSFERED 5052
#define IDC_BUTTON_BILLINGCUSTOMERCHANGE 5053
#define IDC_CHECK_BILLINGREPORT_MBALLOW 5054
#define IDC_CHECK_BILLINGREPORT_MAXCONN 5055
#define IDC_CHECK_BILLINGREPORT_EXCESSCHARGES 5056
#define IDC_CHECK_BILLINGREPORT_TOTALCHARGES 5057
#define IDC_EDIT_BILLINGREPORTTITLE     5058
#define IDC_EDIT_BILLINGCURRENCY        5059
#define IDC_EDIT_BILLING_CUSTOMERNAME   5060
#define IDC_EDIT_BILLINGCUSTOMERID      5061
#define IDC_EDIT_BILLINGCUSTOMERURL     5062
#define IDC_EDIT_BILLINGCUSTOMERFIXEDCHARGE 5063
#define IDC_EDIT_BILLINGCUSTOMERFIXEDNUMBER 5064
#define IDC_EDIT_BILLINGCUSTOMEREXCESSCHARGE 5065
#define IDC_EDIT_BILLINGCUSTOMEREXCESSNUMBER 5066
#define IDC_CHECK_BILLINGCUSTOMEREXCESSCHARGE 5067
#define IDS_MENU_VIEWSCHEDULETRANSCRIPT 5068
#define IDS_MENU_REMOVESELECTEDLOGS     5069
#define IDS_MENU_EDITLOGS               5070
#define IDS_MENU_COMPRESSLOGTOGZIP      5071
#define IDS_MENU_COMPRESSLOGTOBZIP2     5072
#define IDS_MENU_SHOWLOGDURATION        5073
#define IDS_MENU_ADDLOGSTOLIST          5074
#define IDS_MENU_SAVELIST               5075
#define IDS_MENU_LOADLIST               5076
#define IDS_MENU_WEBADMINCONFIG         5077
#define IDS_MENU_SELECTNEWSKIN          5078
#define IDS_MENU_LANGUAGEBUILDER        5079
#define IDS_MENU_INSTALLAUTOSTART       5080
#define IDS_MENU_FWCWEBSITE             5081
#define IDS_BILLINGCHARGESLIST          5082
#define IDS_BILLINGCHARGES_FIXED        5083
#define IDS_BILLINGCHARGES_EXCESS       5084
#define IDS_BILLINGSETUP_PERIOD         5085
#define IDS_BILLINGSETUP_OUTPUTFORMAT   5086
#define IDM_ABOUT                       40001
#define IDM_ACWWW                       40002
#define IDM_CHECKFORUPDATE              40003
#define IDM_CLEARLIST                   40004
#define IDM_COPY                        40005
#define IDM_EXIT                        40006
#define IDM_FILE_RECENTSETTINGS_RECENTFILE 40007
#define IDM_FM_COPY                     40008
#define IDM_FTPOPEN                     40009
#define IDM_FTPPROCESS                  40010
#define IDM_GROW                        40011
#define IDM_HELP                        40012
#define IDM_HELPCONTENTS                40013
#define IDM_INSTALLNTS                  40014
#define IDM_INSTALLNTSBOOT              40015
#define IDM_LOGS_ADDLOGS                40016
#define IDM_LOGS_CLEARLOGS              40017
#define IDM_LOGS_COMPLOG                40018
#define IDM_LOGS_COMPLOG2               40019
#define IDM_LOGS_EDITLOGS               40020
#define IDM_LOGS_LOADLOGS               40021
#define IDM_LOGS_PROCESSLOGS            40022
#define IDM_LOGS_REMOVELOGS             40023
#define IDM_LOGS_SAVELOGS               40024
#define IDM_LOGS_VIEWLOGS               40025
#define IDM_MONITORFILE                 40026
#define IDM_NEW                         40027
#define IDM_NEWAPP                      40028
#define IDM_ONLINEMANUAL                40029
#define IDM_OPEN                        40030
#define IDM_PASTE                       40031
#define IDM_PREFS                       40032
#define IDM_PREFS_1                     40033
#define IDM_PREFS_2                     40034
#define IDM_PREFS_3                     40035
#define IDM_PREFS_4                     40036
#define IDM_PREFS_5                     40037
#define IDM_PREFS_6                     40038
#define IDM_PREFS_7                     40039
#define IDM_PREFS_8                     40040
#define IDM_PREFS_9                     40041
#define IDM_PROCESS                     40042
#define IDM_APPWWW                      40043
#define IDM_REMOVENTS                   40044
#define IDM_SAVE                        40045
#define IDM_SAVEAS                      40046
#define IDM_SCHED_CLEAR                 40047
#define IDM_SCHED_DELETE                40048
#define IDM_SCHED_DISABLEALL            40049
#define IDM_SCHED_DISABLETHIS           40050
#define IDM_SCHED_ENABLEALL             40051
#define IDM_SCHED_ENABLETHIS            40052
#define IDM_SCHED_NEW                   40053
#define IDM_SCHED_PROPERTIES            40054
#define IDM_SCHED_RUNNOW                40055
#define IDM_SCHED_TRANSCRIPT            40056
#define IDM_SCHEDULE                    40057
#define IDM_SHOWNTSERVICES              40058
#define IDM_SHRINK                      40059
#define IDM_STOP                        40060
#define IDM_STOPALL                     40061
#define IDM_SUPPORTWWW                  40062
#define IDM_UPDATEONOFF                 40063
#define IDM_VIEWHTML                    40064
#define IDM_VIEWTRANSCRIPT              40065
#define IDM_BACKGROUNDGRAD              40066
#define IDM_HELP_SUPPORTZONESETUP       40067
#define IDM_HELP_CHANGESUPPORTPASSWORD  40068
#define IDM_MUSIC1                      40069
#define IDM_WEBCHAT                     40070
#define IDM_STOCK                       40071
#define IDM_ORDERWWW                    40072
#define IDM_LANGBUILDER                 40073
#define IDM_STARTUPSERVICE              40074
#define IDM_ENDSERVICE                  40075
#define IDM_HELPTOPICS                  40076
#define IDM_HELPSEARCH                  40077
#define IDM_HELPHELP                    40078
#define IDM_UNDO                        40079
#define IDM_CUT                         40080
#define IDM_LINK                        40081
#define IDM_LINKS                       40082
#define IDM_LOGS_REVERT                 40083
#define IDM_LOGS_SHOW_DURATION          40084
#define ID_Menu                         40087
#define IDM_NEW_STREAMING               40088
#define IDM_NEW_FW                      40089
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        1098
#define _APS_NEXT_COMMAND_VALUE         40090
#define _APS_NEXT_CONTROL_VALUE         5082
#define _APS_NEXT_SYMED_VALUE           7001
#endif
#endif
