/* resource_strings.c */

/* Change History

	27/07/01	RHF		Added missing include for myansi.h
	
*/

#include "FWA.h"

#include "myansi.h"

#include "resource_strings.h"
typedef struct { long id; char *szText; } Resource_strings ;

Resource_strings _res_strings[] = {
	    IDS_DATEEND,            "Report up to this date",
	    IDS_DATEFMT,            "None,Fri  07 Mar 1997,DD/MMM/YYYY,MM/DD/YY,DD/MM/YY,YYYY-MM-DD,Thu Aug  1 10:32:18 1996,Unix Time,[06/Aug/2000:14:59:29 -0400]",
	    IDS_DATEFORMAT,         "Auto,DD/MM/YY,MM/DD/YY,YY/MM/DD",
	    IDS_DATEOFFSET,         "Adjust all times by this amount",
	    IDS_DATEOVERIDE,        "If the date format cannot be detected, overide it with this",
	    IDS_DATES,              "Specify Date,All dates,Today,Yesterday,This Week,Week Before,Last 7 days,Last 14 days,Last 21 days,Last 28 days,This Month,Month Before,This Quarter,Prev Quarter,This 6 months,Last 6 months,This Year,Year Before,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Last Complete 7 days,Last Complete 14 days,Last Complete 21 days,Last Complete 28 days",
	    IDS_DATESTART,          "Report from this date onwards",
	    IDS_DATETOKENS,         "Day of Month {DD},Month {MM},Month Name {MMM},Year {YYYY},Year {YY},Log Date Start {DD_BEG},Log Date Ending Year {YY_END}",
	    IDS_DEC,                "Dec",
	    IDS_DELETEFTP,          "Deleting ftp file %s",
	    IDS_DISCONNECT,         "Disconnected...",
	    IDS_DISCONREMOTE,       "&Disconnect remote connection",
	    IDS_DNSCLEARED,         "Your DNS cache has been cleared.",
	    IDS_DNSCOMPLETE,        "DNS Completed",
	    IDS_DONE,               "Done.",
	    IDS_DOWNLOADING,        "Downloading %s ...",
	    IDS_DOWNLOADINGKB,      "Downloading %s...%d KB (%.2f%%)",
	    IDS_DOWNLOADSTOP,       "Download has been cancelled",
	    IDS_EDITPATH,           "Virtual Host,Output Path",
	    IDS_EDITSCHEDULE,       "Edit Schedule",
	    IDS_EDITSET,            "Editing Settings",
	    IDS_EMAILNOTIFY,        "Emailing notification message...",
	    IDS_ENDSERVICE,         "Ending NTService... please wait",
	    IDS_ERR_BADLOG,         "No valid data processed, because the log file is not recognized.",
	    IDS_ERR_CANTOPENLOG,    "Cannot open log file '%s'",
	    IDS_ERR_CANTSAVE,       "Could not save the settings file\n%s",
	    IDS_ERR_CONNECTING,     "Error connecting to ftp server (%s) as user (%s) because ..\n%s.",
	    IDS_ERR_DATE1,          "The start date is incorrectly formated\nCorrect format is MM/DD/YYYY",
	    IDS_ERR_DATE2,          "The end date is incorrectly formated\nCorrect format is MM/DD/YYYY",
	    IDS_ERR_DATE3,          "The start date %s cannot be after the end date %s\nplease change",
	    IDS_ERR_DATERANGE,      "No valid data processed,\nbecause the date range (%s - %s)\nignored all hits from (%s - %s).\n",
	    IDS_ERR_FILEFAILED,     "Error, failed to open local file (%s)",
	    IDS_INSTALLNTS,         "Installing NTService...",
	    IDS_INSTALLNTSBOOT,     "Installing NTService autostart...",
	    IDS_JAN,                "Jan",
	    IDS_JUL,                "Jul",
	    IDS_JUN,                "Jun",
	    IDS_LANG,               "English,German,Italian,French,Spanish,Swedish,Norwegian,Danish,Dutch,Japanese",
	    IDS_LANGBUILDER_LISTTITLES,"Text Category,English (Default),",
	    IDS_LANGTOKEN_EXIT,     "Exits the Language Builder dialog.",
	    IDS_LANGTOKEN_FIND,     "Press to activate a search for the text.",
	    IDS_LANGTOKEN_FINDTEXT, "Search text to find  (Press F3 or return to activate a search).",
	    IDS_LANGTOKEN_LANG,     "List of languages currently available to edit.",
	    IDS_LANGTOKEN_LIST,     "Language strings, contains the default & currently selected language.",
	    IDS_LANGTOKEN_SAVEAS,   "Save current language string to a new file.",
	    IDS_LANGTOKEN_TEXT,     "Text of the current item. (Press return to update text). ",
	    IDS_LANGTOKEN_UPDATE,   "Updates the currently selected item in the list.",
	    IDS_LITTLEDISKSPACE,    "Low on disk space:There is possible not enough disk space free (%x Kb) for a report to be written to.\nProceed any way ?",
	    IDS_LOADDATABASE,       "Loading database data...",
	    IDS_LOADSETFILE,        "Reading settings file...",
	    IDS_LOADSKIN,           "Loading new skin",
	    IDS_LOCATION,           "Location (%d Kb Free)",
	    IDS_LOGLIST_COL1,       "Server Logs (drag 'n' drop a log file to process)",
	    IDS_LOGLIST_COL2,       "Size           ",
	    IDS_LOGLIST_COL3,       "Format         ",
	    IDS_LOGLIST_COL4,       "Start Date        ",
	    IDS_MAILSENT,           "email sent ok...",
	    IDS_MAKEDEFAULT,        "Making default prefs",
	    IDS_MAKEDIR,            "Makedir?",
	    IDS_MAKEFILEDIR,        "Can not find the path ' %s ' . \r\rWould you like to create the directory?",
	    IDS_MAKEZIP,            "Archiving zip...",
	    IDS_MAR,                "Mar",
	    IDS_MAY,                "May",
	    IDS_MENU_ABOUT,         "About iReporter...",
	    IDS_FILTERSTRING_EXACT_7_EXCLUDE,	                            "This report excludes all user names equal to" ,
	    IDS_FILTERSTRING_EXACT_7_INCLUDE,	                            "This report only includes user names equal to" ,
	    IDS_FILTERSTRING_EXACT_8_EXCLUDE,	                            "This report excludes all URLs that were retrieved using the method" ,
	    IDS_FILTERSTRING_EXACT_8_INCLUDE,	                            "This report only includes URLs that were retrieved using the method" ,
	    IDS_FILTERSTRING_EXACT_9,"This report's focus begins from the URL",
	    IDS_FILTERS_BELOW,      "The filters used in the report are listed below",
	    IDS_KEYVISITORHEADER,   "Key Visitors",
	    IDS_HELP_CARDS,         "Report Descriptions",
	    IDS_ROUTETOKEYPAGE,     "Key Page",
	    IDS_ROUTEFROMKEYPAGE,   "Key Page",
	    IDS_TABREPORT2,         "Output,Page,Style,Options",
	    IDS_TABROUTES,          "Key Visitors,Route To Key Pages,Route From Key Pages",
	    IDS_ICON_NAMESFIREWALL, "Pre Process,Report,Analysis,Filters,Statistics,Tracking,Advertising,Virtual,Post Process,Custom  Format,Proxy/Firewalls,Debug",
	    IDS_MENU_CONVERT2W3C,   "Convert log file to W3C Format",
	    IDS_STATSTYLES,         "Web Servers, Proxies, Streaming Media, Firewalls",
	    IDS_LOGLIST_COL5,       "End Date          ",
	    IDS_LOGLIST_COL6,       "Duration          ",
	    IDS_CONFIRM_DB_DELETE,  "All accumulated statistics within ""%s"" will be lost.\nDo you really wish to delete this file?",
	    IDS_DB_DELETED_OK,      "Successfully deleted file ""%s"".",
	    IDS_DB_DELETE_FAILED,   "Could not delete file ""%s"".",
	    IDS_DB_DOES_NOT_EXIST,  "The file ""%s"" does not exist.",
	    IDS_MENU_CONVERT2W3C_STATUS,"Convert selected log file(s) to W3C format",
	    IDS_PREFROUTER_CHANGE,  "Change address",
	    IDS_PREFROUTER_CLR,     "Remove all addresses",
	    IDS_PREFROUTER_NAME,    "Internal address of network to be added (eg. 192.168.* )",
	    IDS_PREFROUTER_REM,     "Delete internal address",
	    IDS_PREFSTAT_SESSIONTIME,	                            "The amount of time that defines a new session between successive hits" ,
	    IDS_PREFVD_ADD,         "Add virtual host map",
	    IDS_PREFVD_CLR,         "Clear all virtual host names",
	    IDS_PREFVD_CLUSTER,     "Enable multi-server clustering log processing",
	    IDS_PREFVD_COST,        "Cost per megabyte of data",
	    IDS_PREFVD_MONTHLY,     "Produce a report per month of a log file",
	    IDS_PREFVD_NAME,        "New virtual host name",
	    IDS_PREFVD_REM,         "Delete virtual host map",
	    IDS_PREFVD_SEQDIR,      "Store Virtual Domains in sequential numbered directories instead",
	    IDS_PREFVD_WEEKLY,      "Produce a report per week of a log file",
	    IDS_PREPROCESS,         "Pre-Processing",
	    IDS_PROCESSCLIENTS,     "Processing visitors...",
	    IDS_PROCESSFROMLIST,    "Processing logs from history list",
	    IDS_PROCESSING,         "Processing...",
	    IDS_PROCESSLOG,         "Process user selected logs...",
	    IDS_QUIT,               "Quit.",
	    IDS_RECEIVELOGLIST,     "Receiving logs list...",
	    IDS_REFERHEADER,        "Referral Pattern,Name",
	    IDS_REG,                "&Register iReporter ...",
	    IDS_REGISTMSG1,         "If you haven't registered your iReporter product, please do so now.\nBy registering, you can gain access to regular updates and technical support.\n\n",
	    IDS_REGISTMSG2,         "You will also be eligible to receive product announcements, special offers,\nand information on upcoming events.\n\nRegister Now?\n",
	    IDS_REGISTONLINE,       "Register Online Now?",
	    IDS_REGNOTCREATE,       "Could not create Registry Value '%s' - '%s', retcode=%d",
	    IDS_REGONLINE,          "Register iReporter &online...",
	    IDS_REMOTEADDLOG,       "Remote add log...",
	    IDS_REMOTEDISCON,       "Remote Disconnecting...",
	    IDS_REMOTEGETCONFG,     "Remote get config...",
	    IDS_REMOTELOG,          "Processing remote Log %s",
	    IDS_CANCELLED,          "Cancelled Processing.",
	    IDS_CANCELLED_ODBC_DB,  "Cancelled processing ODBC Database.",
	    IDS_CANNOTEDIT,         "Cannot edit settings during a running schedule",
	    IDS_CLEAN,              "Cleaning up...",
	    IDS_CLEARCACHE,         "Clear the whole internal DNS cache from disk",
	    IDS_COLORSCHEME_BASIC,  "Basic",
	    IDS_COLORSCHEME_BLAND,  "Bland",
	    IDS_COLORSCHEME_BLUE,   "Blue",
	    IDS_COLORSCHEME_DEFAULT,"Default",
	    IDS_COLORSCHEME_GREY,   "Grey",
	    IDS_COLORSCHEME_ICE,    "Ice",
	    IDS_COLORSCHEME_RANDOM, "Random",
	    IDS_COLORSCHEME_WILD,   "Wild",
	    IDS_COMMENTS,           "Comments",
	    IDS_COMPRESSDONE,       "Compressed %d Kb to %d Kb (%d%%) done.",
	    IDS_COMPRESSED,         "Your log file been compressed.\n\n",
	    IDS_COMPRESSING,        "Compressing %d%% (%d Kb)...",
	    IDS_CONFIG,             "Receiving config...",
	    IDS_CONNECT,            "Connecting....",
	    IDS_CONNECTED,          "Connected Ok.",
	    IDS_CONNECTINGTO,       "Connecting to ftp %s@%s...",
	    IDS_CONNECTTOREMOTE,    "Connect to &remote iReporter ...",
	    IDS_COOKIEVAR,          "Define a cookie variable to get the username or unique field from",
	    IDS_COPYINGFILE,        "Coping file %s",
	    IDS_COUNTRIES,          "Countries",
	    IDS_CUSTOM_DATA,        "Which field to edit",
	    IDS_CUSTOM_DATE,        "Format of the date field",
	    IDS_CUSTOM_INFO,        "Custom Format summary",
	    IDS_CUSTOM_POS,         "The field's position within the data, 1 to 25",
	    IDS_CUSTOM_SEP,         "Seperator to use between fields   , or \\t or a space",
	    IDS_CUSTOM_TIME,        "Format of the time field",
	    IDS_CUSTOM_USE,         "Use custom format instead of autodetection",
	    IDS_REMOTEPROCESS,      "Remote process...",
	    IDS_REMOTEPROCESSLIST,  "Remote process list...",
	    IDS_REMOTESHOW,         "Remote show loglist...",
	    IDS_REMOTESTOP,         "Remote stopping...",
	    IDS_REMOVENTS,          "Removing NTService...",
	    IDS_REPORT_CAT,         "Report Categories",
	    IDS_REPORT_PDF_GRAPHFONT,"Tiny,Small,Normal,Large",
	    IDS_REPORT_PDFFONT,     "Times New Roman,Helvetica",
	    IDS_REPORT_PDFFONTSTYLES,"Normal,Bold,Italic,Bold Italic",
	    IDS_REPORT_PDFPAGENUMBERINGPOS,	                            "None,TopAndBottomMiddle,TopAndBottomRight,TopMiddle,TopRight,BottomMiddle,BottomRight" ,
	    IDS_REPORT_PDFPAGESIZES,"USLetter,USLetter Landscape,A4,A4 Landscape,Custom",
	    IDS_REPORT_PDFSPACING,  "After banner,After graph,After table",
	    IDS_REPORT_PDFTABLETEXTNAME,"Table Title,Column Headings,Column Data",
	    IDS_REPORT_PDFTRUNCATETEXT,"Left,Right,Left Ellipsis,Right Ellipsis",
	    IDS_REPORT_TITLES,      "Report Titles",
	    IDS_REPORTFORMAT,       "HTML,HTML Framed,Word (RTF),Comma Delimited,PDF,Excel",
	    IDS_SAVEDATABASE,       "Saving database ...",
	    IDS_SAVETODATABASE,     "Do you want to save this log file ' %s ' to database ?\r\rIf you select yes, please provide data source name and table name in the next steps.",
	    IDS_SCH_CANCEL,         "Schedule is cancelled.",
	    IDS_SCH_HEADERS,        "#    ,Name        ,LogFile     ,Active,Start Date/Time  ,Repeat  ,Next Schedule    ,Settings File              ",
	    IDS_SCH_NOEDIT,         "Cannot edit schedule during active events",
	    IDS_SCH_NOEDIT2,        "Cannot edit empty schedule",
	    IDS_SCH_NOSETTINGS,     "No settings file can be found.",
	    IDS_SCH_SAVED,          "Schedule is saved.",
	    IDS_SCHEDULEOFF,        "Schedule List Inactive - NTService is handeling the schedules",
	    IDS_SELECTDBASE,        "Select Database or start new ...",
	    IDS_SELECTDOMAIN,       "Select host output path/file...",
	    IDS_SELECTFOLDER,       "Select folder for destination ...",
	    IDS_SELECTLOAD,         "Select Settings File to open...",
	    IDS_SELECTLOADLOGLIST,  "Load log list",
	    IDS_SELECTLOCATION,     "Select a location to create the FileMaker file",
	    IDS_SELECTLOG,          "Select Log File(s), or enter HTTP/FTP URL",
	    IDS_SELECTOUTPUT,       "Select output location and filename",
	    IDS_SELECTSAVE,         "Select Settings file to save...",
	    IDS_SELECTSAVELOG,      "Select log file name to save as...",
	    IDS_SELECTSAVELOGLIST,  "Save log list",
	    IDS_SELECTSKIN,         "Select Skins settings File to open...",
	    IDS_SENDMAILHEADER,     "Sending mail headers...",
	    IDS_SENFCONFIG,         "Sending config to server...",
	    IDS_SEP,                "Sep",
	    IDS_SERVER_ERRORS,      "Server Errors",
	    IDS_SERVER_STATS,       "Server Statistics",
	    IDS_SESSION_LIST,       "Session Listing",
	    IDS_SET,                "Settings",
	    IDS_SETTINGSSAVED,      "Settings saved to",
	    IDS_SHOWLIST,           "Showing log list",
	    IDS_SORTING,            "Name,Bytes Sent,Hits,Pages,Errors,Sessions,Visitors",
	    IDS_SQLCOLTRUNC_WARNG,  "Number of columns in display truncated to %u",
	    IDS_FILTER2,            "File/URL,Visitor,Agent,Referral,Errors,VirtualHost,Cookie,Username,Method,1st Referral in Session",
	    IDS_FILTER3,            "Contains,Starts with,Ends with,Is equal to",
	    IDS_FILTERIN_DATA,      "File/URL pattern to be used (eg, *.html)",
	    IDS_FILTERS,            "Rules,Type,Logic,Data",
	    IDS_FRAMEDHTML,         "Make report in a framed html output",
	    IDS_GENERAL_LABELS,     "General Labels",
	    IDS_GETURLTITLE,        "Getting URL title...",
	    IDS_GLOB_PAGEADD,       "Add a new page or download extension to the list",
	    IDS_GLOB_PAGECLR,       "Reset all extensions to the default original list",
	    IDS_GLOB_PAGEREM,       "Remove a page or download extension",
	    IDS_GROUPHEADER,        "URL Pattern,Name",
	    IDS_HIDELIST,           "Hiding list",
	    IDS_ICON_NAMES,         "Pre Process,Report,Analysis,Filters,Statistics,Virtual,Post Process,Custom  Format,Debug",
	    IDS_ICON_NAMESENT,      "Pre Process,Report,Analysis,Filters,Statistics,Tracking,Advertising,Virtual,Post Process,Custom  Format,Debug",
	    IDS_IMAGETYPE,          "GIF,JPEG,PNG",
	    IDS_INFO,               "Information",
	    IDS_ADDCAMP_ADD,        "Add Campaign Details",
	    IDS_ADDCAMP_COST,       "Campaign Cost per month",
	    IDS_ADDCAMP_NAME,       "Campaign name",
	    IDS_ADDCAMP_PATTERN,    "Campaign View URL Pattern",
	    IDS_ADDCAMP_REM,        "Delete Campaign Item",
	    IDS_ADDHEADER,          "Description,File Name,Click String",
	    IDS_ADDHEADER2,         "Description,Referral,Cost",
	    IDS_APPLY_ALL,          "Apply All",
	    IDS_APPLY_GROUP,        "Apply Group",
	    IDS_APPLYALL,           "Apply settings to all of the statistics",
	    IDS_APR,                "Apr",
	    IDS_AUG,                "Aug",
	    IDS_BACKGROUND,         "Graduated Background GUI",
	    IDS_BUILD,              "Build",
	    IDS_BUILTON,            "Built on",
	    IDS_CANCELFILEMAKER,    "Cancelled creating FileMaker file.\r\rThe log file will not been saved to ' %s'",
	    IDS_TIPTABSIZE,         "The amount of items listed in a stats table",
	    IDS_TIPVDREPORTBY,      "Determine how to handle logs with virtual host",
	    IDS_TIPVDSORTBY,        "Sort the virtual report list by this",
	    IDS_TIPVIEW,            "Display Report output in your browser (use ALT-key to force IE)",
	    IDS_TOKENS,             "These are some sample date tokens you can use to automatically place in filenames/URLs",
	    IDS_TOOLBARSERVICE,     "NTService: Installed",
	    IDS_UPLOADED,           "Your usage report has been uploaded to %S.\n\n",
	    IDS_UPLOADINGTO,        "Uploading to %s...",
	    IDS_UPLOADLOGS,         "Uploading log files...",
	    IDS_UPLOADREPORT,       "Uploading report files...",
	    IDS_USEGRAPH,           "Activate the image graph in the report",
	    IDS_VDREPORTBY,         "None,Log File,Virtual Host,Top Level Directory,Second Level Directory,Specific Directory,Visitor",
	    IDS_VDSORTBY,           "Name,Bytes Sent,Hits,Pages,Date",
	    IDS_VMAPHEADER,         "Old Host name,New Host name",
	    IDS_WARN_MANYFILES,     "Continue Now ? :WARNING!, Processing using these settings may produce thousands of session history files.",
	    IDS_WEB,                "Web &Admin Configuration...",
	    IDS_WIZARD,             "&Begin Wizard...",
	    IDS_WRITEGRAPH,         "Writing %s Graph...",
	    IDS_WRITEGRAPH_DONE,    "Writing %s Graph done.",
	    IDS_WRITEREPORT,        "Writing %s ...",
	    IDS_WRITEREPORT_DONE,   "Writing %s done.",
	    IDS_WRITINGHOST,        "Writing Virtualhosts",
	    IDS_WRITINGREPORT,      "Writing report %d '%s'...",
	    IDS_ZIPFINISH,          "Your usage report has been compressed. You can access it at %s\n\n",
	    IDS_LANG_SAVEAS,        "Save language as",
	    IDS_ADDCAMP_CHANGE,     "Change",
	    IDS_WIZARDGUIMSG,       "Please specify a valid log file!",
	    IDS_NEXT,               "Next.",
	    IDS_STRING_REMOVETHIS,  "No help available",
	    IDS_CLUSTERHEADER,      "Name    ,IP Address,Path Pattern            ",
	    IDS_FILTERSTRING_0_EXCLUDE,"This report excludes all URLs that",
	    IDS_FILTERSTRING_0_INCLUDE,"This report includes only URLs that",
	    IDS_MENU_SUPPORTWWW,    "Support website for help",
	    IDS_MENU_UPDATEONOFF,   "Select me to toggle this on/off.",
	    IDS_MENU_VIEWHTML,      "View report",
	    IDS_MENU_WIZARD,        "Run Wizard Configuration",
	    IDS_MSG_CLEARSCH,       "Clear Schedule: Are you sure you wish to clear the schedule?",
	    IDS_MSG_NOREPORT,       "No Report to view:No current report has been generated by this scheduled event!",
	    IDS_MSG_OPENYESNO,      "Information:Are you sure you want to open %s?",
	    IDS_MSG_SAVESETTINGS,   "Save Settings ?:Save changes to %s?",
	    IDS_NETINIT_ERR,        "Net initilization error! You may want to switch DNS Lookups Off",
	    IDS_NEWSKIN,            "Selecting new skin",
	    IDS_NODISKSPACE,        "There is no diskspace left to write reports, only %ld Kb left",
	    IDS_NOSETTINGSFILE,     "No Settings file can be found/opened",
	    IDS_NOTABLE,            "Not any table in the database",
	    IDS_NOTENOUGH,          "Not enough memory!!!",
	    IDS_NOV,                "Nov",
	    IDS_OCT,                "Oct",
	    IDS_OK,                 "Ok.",
	    IDS_OPENFILEMAKER,      "Please open FileMaker file '%s'  \r\rif it is not opened.",
	    IDS_OPTIONS_OFF,        "Options Off",
	    IDS_OPTIONS_ON,         "Options ON",
	    IDS_ORDER,              "&Order iReporter online...",
	    IDS_ORGANIZATIONS,      "Organizations",
	    IDS_ORGHEADER,          "Domain Pattern,Organization Name",
	    IDS_OUTDIR,             "Output path of report",
	    IDS_PP_BROWSE,          "Select a folder path to place the report",
	    IDS_PP_COMPRESSLOG,     "Gzip compress the source log file",
	    IDS_PP_DELETEREPORT,    "Delete report from hard disk after uploading",
	    IDS_PP_EMAIL,           "Enter Email destination address",
	    IDS_PP_EMAILSMTP,       "Outgoing SMTP Mail Server",
	    IDS_PP_EMAILSUB,        "Enter Subject",
	    IDS_PP_FTP,             "Select a remote path on ftp to place the report to",
	    IDS_PP_LOCATION,        "Full Path location the report is copied to",
	    IDS_FILTERSTRING_9_EXCLUDE,"This makes no sense to use.",
	    IDS_FILTERSTRING_9_INCLUDE,"This makes no sense to use.",
	    IDS_FILTERSTRING_EXACT_0_EXCLUDE,"This report excludes all URLs titled",
	    IDS_FILTERSTRING_EXACT_0_INCLUDE,"This report includes only URLs titled",
	    IDS_FILTERSTRING_EXACT_1_EXCLUDE,	                            "This report excludes the site visitors whose host address is" ,
	    IDS_FILTERSTRING_EXACT_1_INCLUDE,	                            "This report only includes the site visitors whose host address is" ,
	    IDS_FILTERSTRING_EXACT_2_EXCLUDE,	                            "This report excludes all agent names equal to" ,
	    IDS_FILTERSTRING_EXACT_2_INCLUDE,	                            "This report only includes any agent names equal to" ,
	    IDS_FILTERSTRING_EXACT_3_EXCLUDE,"This report excludes all referals from",
	    IDS_FILTERSTRING_EXACT_3_INCLUDE,"This report only includes referals from",
	    IDS_FILTERSTRING_EXACT_4_EXCLUDE,"This report excludes all errors of type",
	    IDS_FILTERSTRING_EXACT_4_INCLUDE,	                            "This report only includes errors of type" ,
	    IDS_FILTERSTRING_EXACT_5_EXCLUDE,	                            "This report excludes all virtual hosts equal to" ,
	    IDS_FILTERSTRING_EXACT_5_INCLUDE,	                            "This report only includes virtual hosts equal to" ,
	    IDS_FILTERSTRING_EXACT_6_EXCLUDE,	                            "This report excludes all cookies equal to" ,
	    IDS_FILTERSTRING_EXACT_6_INCLUDE,	                            "This report only includes cookies equal to" ,
	    IDS_PP_LOGBROWSE,       "Select a folder path to move the log to",
	    IDS_PP_MSG,             "Enter your Email message here...",
	    IDS_PP_SENDTO,          "Copy the report or zipped report to the location below",
	    IDS_PP_ZIPREPORT,       "Compress the report into one zip file",
	    IDS_PRE_REG,            "Re-register iReporter ...",
	    IDS_PREF_BANDWIDTH,     "Write bandwidth summary information into the report",
	    IDS_PREF_HEADTITLE,     "Include log names in report title",
	    IDS_PREF_LANG,          "Language of the report generated",
	    IDS_PREF_LEFTSIDE,      "Place all names on the right hand column first",
	    IDS_PREF_PDF_PAGESIZE,  "Report output page size",
	    IDS_PREF_QINDEX,        "On each page show quick links to each report page",
	    IDS_PREF_REMOTETITLE,   "Request remote URL titles from pages in report",
	    IDS_PREF_TIMESTAT,      "Write processing time information into the report",
	    IDS_PREFADD_ADD,        "Add Banner Details",
	    IDS_PREFADD_CLR,        "Remove all Banners",
	    IDS_PREFADD_NAME,       "Banner name",
	    IDS_MENU_ORDERWWW,      "Order a copy online now",
	    IDS_MENU_PREFS,         "Edit settings",
	    IDS_MENU_PROCESS,       "Process selected log file(s)",
	    IDS_MENU_PROCESS_ODBC_DB,"Process ODBC Source...",
	    IDS_MENU_REGISTERNOW,   "Register online for support",
	    IDS_MENU_REGISTERSERIAL,"Register serial licence",
	    IDS_MENU_REMOTECONNECT, "Connect to remote Analyzer...",
	    IDS_MENU_REMOTEDISCONNECT,"Disconnect from remote Analyzer...",
	    IDS_MENU_REMOVENTS,     "Remove Service",
	    IDS_MENU_SAVE,          "Save current settings",
	    IDS_MENU_SAVEAS,        "Save current settings to file",
	    IDS_MENU_SCHEDULE,      "Edit schedules",
	    IDS_MENU_SHOWNTSERVICES,"Show Services",
	    IDS_MENU_SHRINK,        "Hide recent log files list",
	    IDS_MENU_STARTUPSERVICE,"Activate Service",
	    IDS_MENU_STOP,          "Stop Processing",
	    IDS_TABSTATSENT,        "Statistics,Global,Organization Groups,Content Groups,Referral Groups",
	    IDS_TABVHOSTS,          "Domains,Aggregation,Mapping,Clustering",
	    IDS_TABVHOSTS2,         "Domains,Aggregation,Mapping",
	    IDS_TIME,               "Time",
	    IDS_TIME_RELATED,       "Time Related",
	    IDS_TIMEFMT,            "None,HH:MM:SS,1:40 PM,Unix Time",
	    IDS_TIMER,              "Minute(s),Hour(s),Day(s),Month(s),Year(s)",
	    IDS_TIPEDIT,            "Edit Report Settings",
	    IDS_TIPAPPHELP,        "Login to Support Zone",
	    IDS_TIPLISTVIEW,        "'Drag and Drop' a log file or shortcut or URL shortcut from IE here to process it.",
	    IDS_TIPOPEN,            "Open a report settings file",
	    IDS_TIPPREFS2,          "Report Settings",
	    IDS_TIPPROCESS,         "Process LOG and generate report",
	    IDS_TIPPROCESS2,        "Process LOG and generate report",
	    IDS_TIPSCHED,           "Prepare and edit a schedule",
	    IDS_TIPSHOWLIST,        "Show/Hide logs file list below",
	    IDS_STOPPED,            "Processing stopped.",
	    IDS_STOREFILEINTEMP,    "Storing file in temp location",
	    IDS_SYSTEM_INFO,        "System Information",
	    IDS_TABADDS,            "Impressions,Campaigns",
	    IDS_TABANALYSIS,        "Options,Network,Extensions,Dynamic",
	    IDS_TABCUSTOM,          "Custom",
	    IDS_TABCUSTOM2,         "Log File,ODBC Table Fields",
	    IDS_TABFILTERS,         "Input Data",
	    IDS_TABPOSTPROC,        "Compress,Upload,Email",
	    IDS_TABPREPROC,         "Download,Options",
	    IDS_TABREPORT,          "Output,Page,Style",
	    IDS_TABPROXY,           "Internal Network",
	    IDS_TABSIZE,            "10 Rows,20 Rows,30 Rows,40 Rows,50 Rows,100 Rows,200 Rows,300 Rows,400 Rows,500 Rows,All Rows",
	    IDS_TABSTATS,           "Statistics,Global,Organization Groups",
	    IDS_TABSTATSDEBUG,      "Statistics,Global,Organization Groups,Content Groups,Referral Groups",
	    IDS_SQLERR_FORMAT,      "SQL Error State:%s, Native Error Code: %lX, ODBC Error: %s",
	    IDS_SQLERRCNTDTITLE,    "SQL_ERROR results continued",
	    IDS_SQLERRMSGTITLE,     "SQL_ERROR results",
	    IDS_SQLEXECERROR,       "Execution Error",
	    IDS_SQLINFO,            "Information",
	    IDS_SQLINITERROR,       "Failed to initialize ODBC interface",
	    IDS_SQLNULLDATASTRING,  "SQL_NULL_DATA",
	    IDS_SQLTRUNCERR,        "Data Truncation",
	    IDS_SQLWRNCNTDTITLE,    "SQL_SUCCESS_WITH_INFO results continued",
	    IDS_SQLWRNMSGTITLE,     "SQL_SUCCESS_WITH_INFO results",
	    IDS_STARTUPSERVICE,     "Starting NTService... please wait",
	    IDS_STAT_NEWVER,        "New Version is available now",
	    IDS_STAT_NOUDPATES,     "No updates available.",
	    IDS_STAT_TABLE,         "Activate the table list in the report",
	    IDS_STATEDIT,           "This is a list of all statistics that can be turned on/off",
	    IDS_STATUST_CMPT,       "Report Completed.",
	    IDS_PREFADD_PATTERN1,   "Banner View URL Pattern",
	    IDS_PREFADD_PATTERN2,   "Banner Click-through URL Pattern",
	    IDS_PREFADD_REM,        "Delete Banner Item",
	    IDS_PREFGEN_DATESTYLE,  "Select which date range applies",
	    IDS_PREFGEN_DNSCACHE,   "Resolve IPs using the cache data only, no internet lookups",
	    IDS_PREFGEN_DNSNO,      "Do not resolve IPs into names, use as is",
	    IDS_PREFGEN_DNSNUM,     "Enter maximum simultaneous DNS lookups",
	    IDS_PREFGEN_DNSYES,     "Resolve IPs into names using internet loookup(slow)",
	    IDS_PREFGEN_FILTERZERO, "Do not include ZERO length files",
	    IDS_PREFGEN_GTYPE,      "Image format the reports contain",
	    IDS_PREFGEN_IGNOREBOOKMARK,	                            "Ignore all bookmarks of file:// referrals in referral list" ,
	    IDS_PREFGEN_IGNORECASE, "Ignore case in all URLs",
	    IDS_PREFGEN_IGNORESELF, "Ignore all referrals from yourself",
	    IDS_PREFGEN_INDEXFILE,  "Default served file ie index.html",
	    IDS_PREFGEN_OUT,        "Choose Output path of report",
	    IDS_PREFGEN_SPLITDATE,  "Normal,Per Week,Per Month",
	    IDS_ERR_FTPREAD,        "Can't open ftp file (%s)\nMaybe path does not exist?",
	    IDS_ERR_FTPWRITE,       "Error, failed to open (%s) for writing.\nMaybe path does not exist?",
	    IDS_ERR_MAKEDIR,        "Cannot find output path (%s)\nbecause %s\nWould you like to make the directory?",
	    IDS_ERR_NOFILTER,       "No valid data processed, because the filter caused all hits to be ignored.",
	    IDS_ERR_NOSETTINGS,     "Settings file %s does not exist",
	    IDS_ERR_OUTPUT,         "Cannot find output path (%s)\nbecause %s\n",
	    IDS_ERR_POSTPROC,       "Your post processing output cannot be the same as the report output path",
	    IDS_ERR_PROCESS,        "Cannot process %s because it is a %s file.",
	    IDS_ERR_REGFAILED,      "Registration failed, exiting iReporter",
	    IDS_ERR_SETTINGSBAD,    "File is not an iReporter settings file",
	    IDS_ERR_SETTINGSFAILED, "Failed to load settings %s",
	    IDS_ERR_UPLOADFAIL,     "Upload log failed\nError connecting to server (%s) as user (%s)",
	    IDS_ERR_ZEROBYTE,       "No valid data processed, because ignore zero byte data ignored all.",
	    IDS_EXT_AUDIO,          "Audio",
	    IDS_EXT_DOWN,           "Downloads",
	    IDS_EXT_PAGES,          "Pages",
	    IDS_EXT_VIDEO,          "Video",
	    IDS_EXTEDIT,            "Page and Download extensions",
	    IDS_FAILED,             "Failed...",
	    IDS_FAILEDCONNECT,      "Failed to connect!",
	    IDS_FAILEDLISTEN,       "failed to listen",
	    IDS_FAILEDMAKEDIR,      "Failed to create directory ' %s '. \r\rCan not write log file to ' %s ",
	    IDS_FAILEDREAD,         "failed reading bytes...",
	    IDS_FAILEDSOCKET,       "Cannot allocate socket",
	    IDS_FAILEDTODOWNLOAD,   "Failed to download",
	    IDS_FAILEDWRITE,        "failed writing bytes...",
	    IDS_FEB,                "Feb",
	    IDS_FIELDFMT,           "Date,Time,Status,Visitor,Source,File,Agent,Bytes,BytesIn,Duration,Referral,UserName,VirtualHost,Method,Protocol,Port",
	    IDS_FILTER_ADD,         "Add Pattern ...",
	    IDS_FILTER_CHANGE,      "Change pattern",
	    IDS_FILTER_REM,         "Remove current selected pattern",
	    IDS_FILTER1,            "Include,Exclude",
	    IDS_PREFGEN_TYPE,       "Report document data format",
	    IDS_PREFGEN_URL,        "Prefix URL for links",
	    IDS_PREFGEN_USECGI,     "Accept cgi parameters to URLs",
	    IDS_PREFGRAPH_3DBARS,   "Use 3D bar graphs instead of 2D",
	    IDS_PREFGRAPH_CORP,     "Use plain white background graphs for easy printing",
	    IDS_PREFGRAPH_WEBPAL,   "Use Netscape 256 color palette for all graphs",
	    IDS_PREFGRAPH_WIDER,    "Use 50% wider graphs",
	    IDS_PREFGRP_ADD,        "Add Group",
	    IDS_PREFGRP_CLR,        "Remove all groups",
	    IDS_PREFGRP_NAME,       "Group name",
	    IDS_PREFGRP_REM,        "Delete Group",
	    IDS_PREFHTML_FOOT,      "HTML code for Report footers",
	    IDS_PREFHTML_HEAD,      "HTML code for Report headers",
	    IDS_PREFHTML_RGB1,      "Default colors to use in each table list",
	    IDS_PREFHTML_RGB2,      "Default colors to use in each table list",
	    IDS_PREFHTML_RGB3,      "Default colors to use in each table list",
	    IDS_PREFHTML_RGB4,      "Default colors to use in each table list",
	    IDS_PREFHTML_RGB5,      "Default colors to use in each table list",
	    IDS_PREFHTML_RGB6,      "Default colors to use in each table list",
	    IDS_PREFNOTIFY_ADD,     "Add notify",
	    IDS_PREFNOTIFY_CLR,     "Clear all notifys",
	    IDS_PREFNOTIFY_NAME,    "New notify name",
	    IDS_PREFNOTIFY_REM,     "Delete notify",
	    IDS_PREFORG_ADD,        "Add organization",
	    IDS_PREFORG_CLR,        "Remove all organizations",
	    IDS_PREFORG_DEFAULT,    "Add default organizations",
	    IDS_PREFORG_NAME,       "Organization name",
	    IDS_PREFORG_REM,        "Delete organization",
	    IDS_PREFREF_ADD,        "Add Referral",
	    IDS_PREFREF_CLR,        "Remove all referrals",
	    IDS_PREFREF_NAME,       "Referral name",
	    IDS_PREFROUTER_ADD,     "Add internal address",
	    IDS_MENU_ACWWW,         "Open browser to display Funnel Web web site",
	    IDS_MENU_BACKGROUNDGRAD,"Toggle gradient backgrounds",
	    IDS_MENU_CHECKFORUPDATE,"Check if a new update is available",
	    IDS_MENU_CLEARLIST,     "Clear recent log files list",
	    IDS_MENU_CONVERT_TO_ODBC,"Convert log file to ODBC",
	    IDS_MENU_ENDSERVICE,    "Stop active Service",
	    IDS_MENU_EXIT,          "Quit Analyzer",
	    IDS_MENU_FTPPROCESS,    "Open remote log file on ftp server",
	    IDS_MENU_GROW,          "Show recent log files list",
	    IDS_MENU_HELP,          "Display Analyzer manual via PDF",
	    IDS_MENU_INSTALLNTS,    "Install Analyzer as a Windows/NT Service",
	    IDS_MENU_MONITORFILE,   "View log file in list",
	    IDS_MENU_NEW,           "Open a new set of default settings as Untitled.fwp",
	    IDS_MENU_NEWAPP,       "Run a new copy of Analyzer",
	    IDS_MENU_ONLINEMANUAL,  "Online manual",
	    IDS_MENU_OPEN,          "Open an existing Settings (.fwp) file",
	    IDS_ABOUT,              "About",
	    IDS_FILTERSTRING_1_EXCLUDE,	                            "This report excludes all site visitors whose host addresses" ,
	    IDS_FILTERSTRING_1_INCLUDE,	                            "This report includes only site visitors whose host addresses" ,
	    IDS_FILTERSTRING_2_EXCLUDE,"This report excludes all agents that",
	    IDS_FILTERSTRING_2_INCLUDE,"This report includes only agents that",
	    IDS_FILTERSTRING_3_EXCLUDE,	                            "This report excludes all referals whose host addresses" ,
	    IDS_FILTERSTRING_3_INCLUDE,	                            "This report includes only referals whose host addresses" ,
	    IDS_FILTERSTRING_4_EXCLUDE,"This report excludes all errors that",
	    IDS_FILTERSTRING_4_INCLUDE,"This report includes only errors that",
	    IDS_FILTERSTRING_5_EXCLUDE,"This report excludes all virtual hosts that",
	    IDS_FILTERSTRING_5_INCLUDE,"This report includes only virtual hosts that",
	    IDS_FILTERSTRING_6_EXCLUDE,"This report excludes all cookies that",
	    IDS_FILTERSTRING_6_INCLUDE,"This report includes only cookies that",
	    IDS_FILTERSTRING_7_EXCLUDE,"This report excludes all user names that",
	    IDS_FILTERSTRING_7_INCLUDE,"This report includes only user names that",
	    IDS_FILTERSTRING_8_EXCLUDE,"This report excludes all methods that",
	    IDS_FILTERSTRING_8_INCLUDE,"This report includes only methods that",
	0,0
};

char *ReturnString( long id ) {
	int x=0 ;
	while( _res_strings[x].id )
	{	
		if ( _res_strings[x].id == id ) return _res_strings[x].szText;
		x++;
	}
	return 0;
}

void GetString( long id, char *dest, int len )
{
	strcpy( dest, ReturnString( id ) );
}
