#ifndef __RESSTRINGS_H
#define __RESSTRINGS_H
#ifdef __cplusplus
extern "C" {
#endif
#define IDS_ABOUT                       591
#define IDS_ADDCAMP_ADD                 592
#define IDS_ADDCAMP_COST                593
#define IDS_ADDCAMP_NAME                594
#define IDS_ADDCAMP_PATTERN             595
#define IDS_ADDCAMP_REM                 596
#define IDS_ADDHEADER                   597
#define IDS_ADDHEADER2                  598
#define IDS_APPLY_ALL                   599
#define IDS_APPLY_GROUP                 600
#define IDS_APPLYALL                    601
#define IDS_APR                         602
#define IDS_AUG                         603
#define IDS_BACKGROUND                  604
#define IDS_BUILD                       605
#define IDS_BUILTON                     606
#define IDS_CANCELFILEMAKER             607
#define IDS_CANCELLED                   608
#define IDS_CANCELLED_ODBC_DB           609
#define IDS_CANNOTEDIT                  610
#define IDS_CLEAN                       611
#define IDS_CLEARCACHE                  612
#define IDS_COLORSCHEME_BASIC           613
#define IDS_COLORSCHEME_BLAND           614
#define IDS_COLORSCHEME_BLUE            615
#define IDS_COLORSCHEME_DEFAULT         616
#define IDS_COLORSCHEME_GREY            617
#define IDS_COLORSCHEME_ICE             618
#define IDS_COLORSCHEME_RANDOM          619
#define IDS_COLORSCHEME_WILD            620
#define IDS_COMMENTS                    621
#define IDS_COMPRESSDONE                622
#define IDS_COMPRESSED                  623
#define IDS_COMPRESSING                 624
#define IDS_CONFIG                      625
#define IDS_CONNECT                     626
#define IDS_CONNECTED                   627
#define IDS_CONNECTINGTO                628
#define IDS_CONNECTTOREMOTE             629
#define IDS_COOKIEVAR                   630
#define IDS_COPYINGFILE                 631
#define IDS_COUNTRIES                   632
#define IDS_CUSTOM_DATA                 633
#define IDS_CUSTOM_DATE                 634
#define IDS_CUSTOM_INFO                 635
#define IDS_CUSTOM_POS                  636
#define IDS_CUSTOM_SEP                  637
#define IDS_CUSTOM_TIME                 638
#define IDS_CUSTOM_USE                  639
#define IDS_DATEEND                     640
#define IDS_DATEFMT                     641
#define IDS_DATEFORMAT                  642
#define IDS_DATEOFFSET                  643
#define IDS_DATEOVERIDE                 644
#define IDS_DATES                       645
#define IDS_DATESTART                   646
#define IDS_DATETOKENS                  647
#define IDS_DEC                         648
#define IDS_DELETEFTP                   649
#define IDS_DISCONNECT                  650
#define IDS_DISCONREMOTE                651
#define IDS_DNSCLEARED                  652
#define IDS_DNSCOMPLETE                 653
#define IDS_DONE                        654
#define IDS_DOWNLOADING                 655
#define IDS_DOWNLOADINGKB               656
#define IDS_DOWNLOADSTOP                657
#define IDS_EDITPATH                    658
#define IDS_EDITSCHEDULE                659
#define IDS_EDITSET                     660
#define IDS_EMAILNOTIFY                 661
#define IDS_ENDSERVICE                  662
#define IDS_ERR_BADLOG                  663
#define IDS_ERR_CANTOPENLOG             664
#define IDS_ERR_CANTSAVE                665
#define IDS_ERR_CONNECTING              666
#define IDS_ERR_DATE1                   667
#define IDS_ERR_DATE2                   668
#define IDS_ERR_DATE3                   669
#define IDS_ERR_DATERANGE               670
#define IDS_ERR_FILEFAILED              671
#define IDS_ERR_FTPREAD                 672
#define IDS_ERR_FTPWRITE                673
#define IDS_ERR_MAKEDIR                 674
#define IDS_ERR_NOFILTER                675
#define IDS_ERR_NOSETTINGS              676
#define IDS_ERR_OUTPUT                  677
#define IDS_ERR_POSTPROC                678
#define IDS_ERR_PROCESS                 679
#define IDS_ERR_REGFAILED               680
#define IDS_ERR_SETTINGSBAD             681
#define IDS_ERR_SETTINGSFAILED          682
#define IDS_ERR_UPLOADFAIL              683
#define IDS_ERR_ZEROBYTE                684
#define IDS_EXT_AUDIO                   685
#define IDS_EXT_DOWN                    686
#define IDS_EXT_PAGES                   687
#define IDS_EXT_VIDEO                   688
#define IDS_EXTEDIT                     689
#define IDS_FAILED                      690
#define IDS_FAILEDCONNECT               691
#define IDS_FAILEDLISTEN                692
#define IDS_FAILEDMAKEDIR               693
#define IDS_FAILEDREAD                  694
#define IDS_FAILEDSOCKET                695
#define IDS_FAILEDTODOWNLOAD            696
#define IDS_FAILEDWRITE                 697
#define IDS_FEB                         698
#define IDS_FIELDFMT                    699
#define IDS_FILTER_ADD                  700
#define IDS_FILTER_CHANGE               701
#define IDS_FILTER_REM                  702
#define IDS_FILTER1                     703
#define IDS_FILTER2                     704
#define IDS_FILTER3                     705
#define IDS_FILTERIN_DATA               706
#define IDS_FILTERS                     707
#define IDS_FRAMEDHTML                  708
#define IDS_GENERAL_LABELS              709
#define IDS_GETURLTITLE                 710
#define IDS_GLOB_PAGEADD                711
#define IDS_GLOB_PAGECLR                712
#define IDS_GLOB_PAGEREM                713
#define IDS_GROUPHEADER                 714
#define IDS_HIDELIST                    715
#define IDS_ICON_NAMES                  716
#define IDS_ICON_NAMESENT               717
#define IDS_IMAGETYPE                   718
#define IDS_INFO                        719
#define IDS_INSTALLNTS                  720
#define IDS_INSTALLNTSBOOT              721
#define IDS_JAN                         722
#define IDS_JUL                         723
#define IDS_JUN                         724
#define IDS_LANG                        725
#define IDS_LANGBUILDER_LISTTITLES      726
#define IDS_LANGTOKEN_EXIT              727
#define IDS_LANGTOKEN_FIND              728
#define IDS_LANGTOKEN_FINDTEXT          729
#define IDS_LANGTOKEN_LANG              730
#define IDS_LANGTOKEN_LIST              731
#define IDS_LANGTOKEN_SAVEAS            732
#define IDS_LANGTOKEN_TEXT              733
#define IDS_LANGTOKEN_UPDATE            734
#define IDS_LITTLEDISKSPACE             735
#define IDS_LOADDATABASE                736
#define IDS_LOADSETFILE                 737
#define IDS_LOADSKIN                    738
#define IDS_LOCATION                    739
#define IDS_LOGLIST_COL1                740
#define IDS_LOGLIST_COL2                741
#define IDS_LOGLIST_COL3                742
#define IDS_LOGLIST_COL4                743
#define IDS_MAILSENT                    744
#define IDS_MAKEDEFAULT                 745
#define IDS_MAKEDIR                     746
#define IDS_MAKEFILEDIR                 747
#define IDS_MAKEZIP                     748
#define IDS_MAR                         749
#define IDS_MAY                         750
#define IDS_MENU_ABOUT                  751
#define IDS_MENU_ACWWW                  752
#define IDS_MENU_BACKGROUNDGRAD         753
#define IDS_MENU_CHECKFORUPDATE         754
#define IDS_MENU_CLEARLIST              755
#define IDS_MENU_CONVERT_TO_ODBC        756
#define IDS_MENU_ENDSERVICE             757
#define IDS_MENU_EXIT                   758
#define IDS_MENU_FTPPROCESS             759
#define IDS_MENU_GROW                   760
#define IDS_MENU_HELP                   761
#define IDS_MENU_INSTALLNTS             762
#define IDS_MENU_MONITORFILE            763
#define IDS_MENU_NEW                    764
#define IDS_MENU_NEWAPP                765
#define IDS_MENU_ONLINEMANUAL           766
#define IDS_MENU_OPEN                   767
#define IDS_MENU_ORDERWWW               768
#define IDS_MENU_PREFS                  769
#define IDS_MENU_PROCESS                770
#define IDS_MENU_PROCESS_ODBC_DB        771
#define IDS_MENU_REGISTERNOW            772
#define IDS_MENU_REGISTERSERIAL         773
#define IDS_MENU_REMOTECONNECT          774
#define IDS_MENU_REMOTEDISCONNECT       775
#define IDS_MENU_REMOVENTS              776
#define IDS_MENU_SAVE                   777
#define IDS_MENU_SAVEAS                 778
#define IDS_MENU_SCHEDULE               779
#define IDS_MENU_SHOWNTSERVICES         780
#define IDS_MENU_SHRINK                 781
#define IDS_MENU_STARTUPSERVICE         782
#define IDS_MENU_STOP                   783
#define IDS_MENU_SUPPORTWWW             784
#define IDS_MENU_UPDATEONOFF            785
#define IDS_MENU_VIEWHTML               786
#define IDS_MENU_WIZARD                 787
#define IDS_MSG_CLEARSCH                788
#define IDS_MSG_NOREPORT                789
#define IDS_MSG_OPENYESNO               790
#define IDS_MSG_SAVESETTINGS            791
#define IDS_NETINIT_ERR                 792
#define IDS_NEWSKIN                     793
#define IDS_NODISKSPACE                 794
#define IDS_NOSETTINGSFILE              795
#define IDS_NOTABLE                     796
#define IDS_NOTENOUGH                   797
#define IDS_NOV                         798
#define IDS_OCT                         799
#define IDS_OK                          800
#define IDS_OPENFILEMAKER               801
#define IDS_OPTIONS_OFF                 802
#define IDS_OPTIONS_ON                  803
#define IDS_ORDER                       804
#define IDS_ORGANIZATIONS               805
#define IDS_ORGHEADER                   806
#define IDS_OUTDIR                      807
#define IDS_PP_BROWSE                   808
#define IDS_PP_COMPRESSLOG              809
#define IDS_PP_DELETEREPORT             810
#define IDS_PP_EMAIL                    811
#define IDS_PP_EMAILSMTP                812
#define IDS_PP_EMAILSUB                 813
#define IDS_PP_FTP                      814
#define IDS_PP_LOCATION                 815
#define IDS_PP_LOGBROWSE                816
#define IDS_PP_MSG                      817
#define IDS_PP_SENDTO                   818
#define IDS_PP_ZIPREPORT                819
#define IDS_PRE_REG                     820
#define IDS_PREF_BANDWIDTH              821
#define IDS_PREF_HEADTITLE              822
#define IDS_PREF_LANG                   823
#define IDS_PREF_LEFTSIDE               824
#define IDS_PREF_PDF_PAGESIZE           825
#define IDS_PREF_QINDEX                 826
#define IDS_PREF_REMOTETITLE            827
#define IDS_PREF_TIMESTAT               828
#define IDS_PREFADD_ADD                 829
#define IDS_PREFADD_CLR                 830
#define IDS_PREFADD_NAME                831
#define IDS_PREFADD_PATTERN1            832
#define IDS_PREFADD_PATTERN2            833
#define IDS_PREFADD_REM                 834
#define IDS_PREFGEN_DATESTYLE           835
#define IDS_PREFGEN_DNSCACHE            836
#define IDS_PREFGEN_DNSNO               837
#define IDS_PREFGEN_DNSNUM              838
#define IDS_PREFGEN_DNSYES              839
#define IDS_PREFGEN_FILTERZERO          840
#define IDS_PREFGEN_GTYPE               841
#define IDS_PREFGEN_IGNOREBOOKMARK      842
#define IDS_PREFGEN_IGNORECASE          843
#define IDS_PREFGEN_IGNORESELF          844
#define IDS_PREFGEN_INDEXFILE           845
#define IDS_PREFGEN_OUT                 846
#define IDS_PREFGEN_SPLITDATE           847
#define IDS_PREFGEN_TYPE                848
#define IDS_PREFGEN_URL                 849
#define IDS_PREFGEN_USECGI              850
#define IDS_PREFGRAPH_3DBARS            851
#define IDS_PREFGRAPH_CORP              852
#define IDS_PREFGRAPH_WEBPAL            853
#define IDS_PREFGRAPH_WIDER             854
#define IDS_PREFGRP_ADD                 855
#define IDS_PREFGRP_CLR                 856
#define IDS_PREFGRP_NAME                857
#define IDS_PREFGRP_REM                 858
#define IDS_PREFHTML_FOOT               859
#define IDS_PREFHTML_HEAD               860
#define IDS_PREFHTML_RGB1               861
#define IDS_PREFHTML_RGB2               862
#define IDS_PREFHTML_RGB3               863
#define IDS_PREFHTML_RGB4               864
#define IDS_PREFHTML_RGB5               865
#define IDS_PREFHTML_RGB6               866
#define IDS_PREFNOTIFY_ADD              867
#define IDS_PREFNOTIFY_CLR              868
#define IDS_PREFNOTIFY_NAME             869
#define IDS_PREFNOTIFY_REM              870
#define IDS_PREFORG_ADD                 871
#define IDS_PREFORG_CLR                 872
#define IDS_PREFORG_DEFAULT             873
#define IDS_PREFORG_NAME                874
#define IDS_PREFORG_REM                 875
#define IDS_PREFREF_ADD                 876
#define IDS_PREFREF_CLR                 877
#define IDS_PREFREF_NAME                878
#define IDS_PREFROUTER_ADD              879
#define IDS_PREFROUTER_CHANGE           880
#define IDS_PREFROUTER_CLR              881
#define IDS_PREFROUTER_NAME             882
#define IDS_PREFROUTER_REM              883
#define IDS_PREFSTAT_SESSIONTIME        884
#define IDS_PREFVD_ADD                  885
#define IDS_PREFVD_CLR                  886
#define IDS_PREFVD_CLUSTER              887
#define IDS_PREFVD_COST                 888
#define IDS_PREFVD_MONTHLY              889
#define IDS_PREFVD_NAME                 890
#define IDS_PREFVD_REM                  891
#define IDS_PREFVD_SEQDIR               892
#define IDS_PREFVD_WEEKLY               893
#define IDS_PREPROCESS                  894
#define IDS_PROCESSCLIENTS              895
#define IDS_PROCESSFROMLIST             896
#define IDS_PROCESSING                  897
#define IDS_PROCESSLOG                  898
#define IDS_QUIT                        899
#define IDS_RECEIVELOGLIST              900
#define IDS_REFERHEADER                 901
#define IDS_REG                         902
#define IDS_REGISTMSG1                  903
#define IDS_REGISTMSG2                  904
#define IDS_REGISTONLINE                905
#define IDS_REGNOTCREATE                906
#define IDS_REGONLINE                   907
#define IDS_REMOTEADDLOG                908
#define IDS_REMOTEDISCON                909
#define IDS_REMOTEGETCONFG              910
#define IDS_REMOTELOG                   911
#define IDS_REMOTEPROCESS               912
#define IDS_REMOTEPROCESSLIST           913
#define IDS_REMOTESHOW                  914
#define IDS_REMOTESTOP                  915
#define IDS_REMOVENTS                   916
#define IDS_REPORT_CAT                  917
#define IDS_REPORT_PDF_GRAPHFONT        918
#define IDS_REPORT_PDFFONT              919
#define IDS_REPORT_PDFFONTSTYLES        920
#define IDS_REPORT_PDFPAGENUMBERINGPOS  921
#define IDS_REPORT_PDFPAGESIZES         922
#define IDS_REPORT_PDFSPACING           923
#define IDS_REPORT_PDFTABLETEXTNAME     924
#define IDS_REPORT_PDFTRUNCATETEXT      925
#define IDS_REPORT_TITLES               926
#define IDS_REPORTFORMAT                927
#define IDS_SAVEDATABASE                928
#define IDS_SAVETODATABASE              929
#define IDS_SCH_CANCEL                  930
#define IDS_SCH_HEADERS                 931
#define IDS_SCH_NOEDIT                  932
#define IDS_SCH_NOEDIT2                 933
#define IDS_SCH_NOSETTINGS              934
#define IDS_SCH_SAVED                   935
#define IDS_SCHEDULEOFF                 936
#define IDS_SELECTDBASE                 937
#define IDS_SELECTDOMAIN                938
#define IDS_SELECTFOLDER                939
#define IDS_SELECTLOAD                  940
#define IDS_SELECTLOADLOGLIST           941
#define IDS_SELECTLOCATION              942
#define IDS_SELECTLOG                   943
#define IDS_SELECTOUTPUT                944
#define IDS_SELECTSAVE                  945
#define IDS_SELECTSAVELOG               946
#define IDS_SELECTSAVELOGLIST           947
#define IDS_SELECTSKIN                  948
#define IDS_SENDMAILHEADER              949
#define IDS_SENFCONFIG                  950
#define IDS_SEP                         951
#define IDS_SERVER_ERRORS               952
#define IDS_SERVER_STATS                953
#define IDS_SESSION_LIST                954
#define IDS_SET                         955
#define IDS_SETTINGSSAVED               956
#define IDS_SHOWLIST                    957
#define IDS_SORTING                     958
#define IDS_SQLCOLTRUNC_WARNG           959
#define IDS_SQLERR_FORMAT               960
#define IDS_SQLERRCNTDTITLE             961
#define IDS_SQLERRMSGTITLE              962
#define IDS_SQLEXECERROR                963
#define IDS_SQLINFO                     964
#define IDS_SQLINITERROR                965
#define IDS_SQLNULLDATASTRING           966
#define IDS_SQLTRUNCERR                 967
#define IDS_SQLWRNCNTDTITLE             968
#define IDS_SQLWRNMSGTITLE              969
#define IDS_STARTUPSERVICE              970
#define IDS_STAT_NEWVER                 971
#define IDS_STAT_NOUDPATES              972
#define IDS_STAT_TABLE                  973
#define IDS_STATEDIT                    974
#define IDS_STATUST_CMPT                975
#define IDS_STOPPED                     976
#define IDS_STOREFILEINTEMP             977
#define IDS_SYSTEM_INFO                 978
#define IDS_TABADDS                     979
#define IDS_TABANALYSIS                 980
#define IDS_TABCUSTOM                   981
#define IDS_TABCUSTOM2                  982
#define IDS_TABFILTERS                  983
#define IDS_TABPOSTPROC                 984
#define IDS_TABPREPROC                  985
#define IDS_TABREPORT                   986
#define IDS_TABROUTER                   987
#define IDS_TABPROXY                    988
#define IDS_TABSIZE                     989
#define IDS_TABSTATS                    990
#define IDS_TABSTATSDEBUG               991
#define IDS_TABSTATSENT                 992
#define IDS_TABVHOSTS                   993
#define IDS_TABVHOSTS2                  994
#define IDS_TIME                        995
#define IDS_TIME_RELATED                996
#define IDS_TIMEFMT                     997
#define IDS_TIMER                       998
#define IDS_TIPEDIT                     999
#define IDS_TIPAPPHELP                 1000
#define IDS_TIPLISTVIEW                 1001
#define IDS_TIPOPEN                     1002
#define IDS_TIPPREFS2                   1003
#define IDS_TIPPROCESS                  1004
#define IDS_TIPPROCESS2                 1005
#define IDS_TIPSCHED                    1006
#define IDS_TIPSHOWLIST                 1007
#define IDS_TIPTABSIZE                  1008
#define IDS_TIPVDREPORTBY               1009
#define IDS_TIPVDSORTBY                 1010
#define IDS_TIPVIEW                     1011
#define IDS_TOKENS                      1012
#define IDS_TOOLBARSERVICE              1013
#define IDS_UPLOADED                    1014
#define IDS_UPLOADINGTO                 1015
#define IDS_UPLOADLOGS                  1016
#define IDS_UPLOADREPORT                1017
#define IDS_USEGRAPH                    1018
#define IDS_VDREPORTBY                  1019
#define IDS_VDSORTBY                    1020
#define IDS_VMAPHEADER                  1021
#define IDS_WARN_MANYFILES              1022
#define IDS_WEB                         1023
#define IDS_WIZARD                      1024
#define IDS_WRITEGRAPH                  1025
#define IDS_WRITEGRAPH_DONE             1026
#define IDS_WRITEREPORT                 1027
#define IDS_WRITEREPORT_DONE            1028
#define IDS_WRITINGHOST                 1029
#define IDS_WRITINGREPORT               1030
#define IDS_ZIPFINISH                   1031
#define IDS_LANG_SAVEAS                 1032
#define IDS_ADDCAMP_CHANGE              1033
#define IDS_WIZARDGUIMSG                1034
#define IDS_NEXT                        1035
#define IDS_STRING_REMOVETHIS           1036
#define IDS_CLUSTERHEADER               1037
#define IDS_FILTERSTRING_0_EXCLUDE      1038
#define IDS_FILTERSTRING_0_INCLUDE      1039
#define IDS_FILTERSTRING_1_EXCLUDE      1040
#define IDS_FILTERSTRING_1_INCLUDE      1041
#define IDS_FILTERSTRING_2_EXCLUDE      1042
#define IDS_FILTERSTRING_2_INCLUDE      1043
#define IDS_FILTERSTRING_3_EXCLUDE      1044
#define IDS_FILTERSTRING_3_INCLUDE      1045
#define IDS_FILTERSTRING_4_EXCLUDE      1046
#define IDS_FILTERSTRING_4_INCLUDE      1047
#define IDS_FILTERSTRING_5_EXCLUDE      1048
#define IDS_FILTERSTRING_5_INCLUDE      1049
#define IDS_FILTERSTRING_6_EXCLUDE      1050
#define IDS_FILTERSTRING_6_INCLUDE      1051
#define IDS_FILTERSTRING_7_EXCLUDE      1052
#define IDS_FILTERSTRING_7_INCLUDE      1053
#define IDS_FILTERSTRING_8_EXCLUDE      1054
#define IDS_FILTERSTRING_8_INCLUDE      1055
#define IDS_FILTERSTRING_9_EXCLUDE      1056
#define IDS_FILTERSTRING_9_INCLUDE      1057
#define IDS_FILTERSTRING_EXACT_0_EXCLUDE 1058
#define IDS_FILTERSTRING_EXACT_0_INCLUDE 1059
#define IDS_FILTERSTRING_EXACT_1_EXCLUDE 1060
#define IDS_FILTERSTRING_EXACT_1_INCLUDE 1061
#define IDS_FILTERSTRING_EXACT_2_EXCLUDE 1062
#define IDS_FILTERSTRING_EXACT_2_INCLUDE 1063
#define IDS_FILTERSTRING_EXACT_3_EXCLUDE 1064
#define IDS_FILTERSTRING_EXACT_3_INCLUDE 1065
#define IDS_FILTERSTRING_EXACT_4_EXCLUDE 1066
#define IDS_FILTERSTRING_EXACT_4_INCLUDE 1067
#define IDS_FILTERSTRING_EXACT_5_EXCLUDE 1068
#define IDS_FILTERSTRING_EXACT_5_INCLUDE 1069
#define IDS_FILTERSTRING_EXACT_6_EXCLUDE 1070
#define IDS_FILTERSTRING_EXACT_6_INCLUDE 1071
#define IDS_FILTERSTRING_EXACT_7_EXCLUDE 1072
#define IDS_FILTERSTRING_EXACT_7_INCLUDE 1073
#define IDS_FILTERSTRING_EXACT_8_EXCLUDE 1074
#define IDS_FILTERSTRING_EXACT_8_INCLUDE 1075
#define IDS_FILTERSTRING_EXACT_9        1076
#define IDS_FILTERS_BELOW               1077
#define IDS_KEYVISITORHEADER            1078
#define IDS_HELP_CARDS                  1079
#define IDS_ROUTETOKEYPAGE              1080
#define IDS_ROUTEFROMKEYPAGE            1082
#define IDS_TABREPORT2                  1084
#define IDS_TABROUTES                   1086
#define IDS_ICON_NAMESFIREWALL          1087
#define IDS_MENU_CONVERT2W3C            1088
#define IDS_STATSTYLES                  1089
#define IDS_LOGLIST_COL5                1090
#define IDS_LOGLIST_COL6                1091
#define IDS_CONFIRM_DB_DELETE           1092
#define IDS_DB_DELETED_OK               1093
#define IDS_DB_DELETE_FAILED            1094
#define IDS_DB_DOES_NOT_EXIST           1095
#define IDS_MENU_CONVERT2W3C_STATUS     1096
#define kEmptyString 0
char *ReturnString (long id);
void GetString( long id, char *dest, int len );
#ifdef __cplusplus
}
#endif
#endif
